# Generated by Django 2.0.13 on 2019-05-07 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0011_remove_reference_report'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='paper',
            field=models.ForeignKey(help_text='論文レポートなどで，関連する論文がある場合は登録してください．', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_paper', to='paper.Reference', verbose_name='関連論文'),
        ),
    ]
