# Generated by Django 2.0.13 on 2019-05-07 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='paper',
            field=models.ForeignKey(blank=True, help_text='論文レポートなどで，関連する論文がある場合は登録してください．', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_paper', to='paper.Reference', verbose_name='関連論文'),
        ),
    ]
