# Generated by Django 2.0.13 on 2019-06-17 15:10

import django.core.validators
from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20190507_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.FileField(help_text='PDF，Markdown，またはテキストファイルを添付してください．', upload_to=report.models.get_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'txt', 'md'], message='ファイル拡張子は *.pdf ，*.md，*.txt としてください．')], verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(default='No Title', max_length=400),
        ),
    ]
