# Generated by Django 2.0.13 on 2019-10-13 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_auto_20191007_2329'),
        ('report', '0004_auto_20190617_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='research',
            field=models.ForeignKey(blank=True, help_text='研究テーマを説明するためのスライドの場合は，関連するテーマを登録してください．', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_research', to='public.Research', verbose_name='関連テーマ'),
        ),
    ]
