# Generated by Django 2.0.13 on 2019-11-24 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_report_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='research',
            field=models.ForeignKey(blank=True, help_text='研究テーマを説明するためのスライドの場合は，関連するテーマを登録してください．チェックを入れると研究紹介のページに公開されるようになります．', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_research', to='public.Research', verbose_name='関連テーマ'),
        ),
    ]
