# Generated by Django 2.0.13 on 2019-04-05 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assignment_month',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=11, help_text='研究室に配属された月を入力してください．', null=True, verbose_name='卒業・修了(予定)月'),
        ),
        migrations.AddField(
            model_name='student',
            name='assignment_year',
            field=models.IntegerField(blank=True, default=None, help_text='研究室に配属された年を入力してください．', null=True, validators=[django.core.validators.MinValueValidator(2000, message='2000年より前の年は入力できません．'), django.core.validators.MaxValueValidator(2060, message='2060年より先の年は入力できません．')], verbose_name='研究室配属年'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_month',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=3, help_text='卒業・修了・退学・在籍期間終了の(予定)月を入力してください．', null=True, verbose_name='卒業・修了(予定)月'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=None, help_text='卒業・修了・退学・在籍期間終了の(予定)年を入力してください．', null=True, validators=[django.core.validators.MinValueValidator(2010, message='2010年より前の年は入力できません．'), django.core.validators.MaxValueValidator(2060, message='2060年より先の年は入力できません．')], verbose_name='卒業・修了(予定)年'),
        ),
    ]
