# Generated by Django 2.0.13 on 2019-05-08 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190405_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='alma_mater',
            field=models.CharField(blank=True, default='', help_text='出身の高校，高専，大学を入力してください．短期留学生は元々の所属大学を入力してください．', max_length=150, verbose_name='出身校'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_year',
            field=models.IntegerField(blank=True, default=None, help_text='卒業・修了・退学・在籍期間終了の(予定)年を入力してください．大学院に進学希望の場合は，大学院の修了予定年を入力してください．', null=True, validators=[django.core.validators.MinValueValidator(2010, message='2010年より前の年は入力できません．'), django.core.validators.MaxValueValidator(2060, message='2060年より先の年は入力できません．')], verbose_name='卒業・修了(予定)年'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'B3'), (2, 'B4'), (11, 'M1'), (12, 'M2'), (21, 'D1'), (22, 'D2'), (23, 'D3'), (31, '学部卒業'), (32, '修士修了'), (33, '博士修了'), (71, '短期留学生 在籍中'), (72, '短期留学生 在籍期間終了'), (91, '休学'), (92, '退学'), (1001, 'テストユーザ')], default=1, help_text='現在の状態を選択してください．', null=True, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='名前を日本語で入力してください．留学生の場合は，アルファベットではなく，カタカナを使ってください．ミドルネームがある場合は，ここには記載しないでください．', max_length=30, validators=[django.core.validators.RegexValidator(message='全角文字と半角スペースで入力してください．', regex='^[^\\x21-\\x7E]+$')], verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_eng',
            field=models.CharField(help_text='半角英字と半角スペースで，最初の文字を大文字にして入力してください．', max_length=30, validators=[django.core.validators.RegexValidator(message='姓名(英語)は，半角英字と半角スペース，ハイフンで，最初の文字を大文字にして入力してください．', regex='^[A-Z][a-z]+([ \\-A-Za-z]*)$')], verbose_name='名(英語)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_kana',
            field=models.CharField(blank=True, help_text='全角カタカナと半角スペースで入力してください．', max_length=30, validators=[django.core.validators.RegexValidator(message='姓名(フリガナ)は，全角カタカナと半角スペースで入力してください．', regex='^[\\u30A1-\\u30F6 ー]+$')], verbose_name='名(フリガナ)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='名字を日本語で入力してください．留学生の場合は，アルファベットではなく，カタカナを使ってください．ミドルネームがある場合は，半角スペースで区切ってここに記載してください．', max_length=150, validators=[django.core.validators.RegexValidator(message='全角文字と半角スペースで入力してください．', regex='^[^\\x21-\\x7E]+$')], verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_eng',
            field=models.CharField(help_text='半角英字と半角スペースで，最初の文字を大文字にして入力してください．', max_length=150, validators=[django.core.validators.RegexValidator(message='姓名(英語)は，半角英字と半角スペース，ハイフンで，最初の文字を大文字にして入力してください．', regex='^[A-Z][a-z]+([ \\-A-Za-z]*)$')], verbose_name='姓(英語)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_kana',
            field=models.CharField(blank=True, help_text='全角カタカナと半角スペースで入力してください．', max_length=150, validators=[django.core.validators.RegexValidator(message='姓名(フリガナ)は，全角カタカナと半角スペースで入力してください．', regex='^[\\u30A1-\\u30F6 ー]+$')], verbose_name='姓(フリガナ)'),
        ),
        migrations.DeleteModel(
            name='Award',
        ),
    ]
