# Generated by Django 2.0.13 on 2019-08-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190508_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assignment_month',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=11, help_text='研究室に配属された月を入力してください．', null=True, verbose_name='卒業・修了(予定)月'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_month',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=3, help_text='卒業・修了・退学・在籍期間終了の(予定)月を入力してください．', null=True, verbose_name='卒業・修了(予定)月'),
        ),
    ]
