# Generated by Django 2.0.13 on 2019-11-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190831_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lab',
            field=models.BooleanField(default=False, help_text='所属が中川研の場合，チェックを入れてください．', verbose_name='中川研'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, '学士課程3年'), (2, '学士課程4年'), (11, '修士課程1年'), (12, '修士課程2年'), (21, '博士課程1年'), (22, '博士課程2年'), (23, '博士課程3年'), (31, '学部卒業'), (32, '修士修了'), (33, '博士修了'), (71, '短期留学生'), (72, '短期留学生 在籍期間終了'), (91, '休学'), (92, '退学'), (1001, 'テストユーザ')], default=1, help_text='現在の状態を選択してください．', null=True, verbose_name='状態'),
        ),
    ]
