# Generated by Django 2.0.13 on 2019-11-19 23:09

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191104_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', help_text='プロフィール写真のファイルを登録してください．', null=True, upload_to=users.models.get_upload_to, verbose_name='画像ファイル'),
        ),
    ]
