# Generated by Django 2.0.13 on 2019-11-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assignment_month',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=11, help_text='研究室に配属された月を入力してください．', null=True, verbose_name='研究室配属月'),
        ),
    ]
