# Generated by Django 2.0.13 on 2019-11-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191124_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lab',
            field=models.BooleanField(default=False, help_text='所属が中川研の場合，チェックを入れてください．', verbose_name='中川研'),
        ),
    ]
