# Generated by Django 2.0.13 on 2019-11-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_lab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lab',
            new_name='nlab',
        ),
    ]
