# Generated by Django 2.0.13 on 2019-11-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191125_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='room',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='title',
        ),
    ]
