# Generated by Django 2.0.13 on 2019-11-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191125_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='room',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='居室'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='職位'),
        ),
    ]
