# Generated by Django 2.0.13 on 2019-11-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191125_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='url',
            field=models.URLField(blank=True, help_text='個人のウェブページURL', max_length=400, null=True, verbose_name='URL'),
        ),
    ]
