# Generated by Django 2.0.13 on 2020-04-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_teacher_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprivate',
            old_name='email',
            new_name='private_email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.AddField(
            model_name='teacher',
            name='visitor',
            field=models.BooleanField(default=True, help_text='外部の連携研究者の場合，チェックを入れてください．', verbose_name='外部連携研究者'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス'),
        ),
    ]
