# Generated by Django 2.0.13 on 2020-10-02 23:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200408_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyash_qr',
            field=models.ImageField(blank=True, help_text='Kyashの支払いに使うQRコード(自動生成)', upload_to=users.models.get_qr_upload_to, verbose_name='決済QRコード (Kyash)'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyash_url',
            field=models.URLField(blank=True, verbose_name='URL (Kyash)'),
        ),
        migrations.AddField(
            model_name='user',
            name='paypay_qr',
            field=models.ImageField(blank=True, help_text='PayPayの支払いに使うQRコード(自動生成)', upload_to=users.models.get_qr_upload_to, verbose_name='決済QRコード (PayPay)'),
        ),
        migrations.AddField(
            model_name='user',
            name='paypay_url',
            field=models.URLField(blank=True, verbose_name='URL (PayPay)'),
        ),
    ]
