# Generated by Django 2.0.13 on 2020-10-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201002_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='paypay_qr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='paypay_url',
        ),
        migrations.AddField(
            model_name='user',
            name='paypay_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='User ID (PayPay)'),
        ),
    ]
