# Generated by Django 2.0.13 on 2020-10-04 19:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201002_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kyash_url',
        ),
        migrations.AlterField(
            model_name='user',
            name='kyash_qr',
            field=models.ImageField(blank=True, help_text='Kyashの支払いに使うQRコード', upload_to=users.models.get_qr_upload_to, verbose_name='決済QRコード (Kyash)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='paypay_id',
            field=models.CharField(blank=True, help_text='ComNets Marketで物品を販売し，支払いをPayPayで受け取る場合は，PayPayアプリでPayPay IDを設定して，ここに登録してください．', max_length=20, verbose_name='PayPay ID'),
        ),
    ]
