# Generated by Django 2.0.13 on 2021-01-03 01:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201004_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyash_qr',
            field=models.ImageField(blank=True, help_text='ComNets Marketで物品を販売し，支払いをKyashで受け取る場合は，KyashアプリからQRコードを保存して，ここに登録してください．', upload_to=users.models.get_qr_upload_to, verbose_name='決済QRコード (Kyash)'),
        ),
    ]
