# Generated by Django 3.2.5 on 2024-01-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210103_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thesis_b',
            field=models.CharField(blank=True, help_text='卒業論文のタイトルを入力してください．', max_length=300, verbose_name='卒業論文'),
        ),
        migrations.AddField(
            model_name='user',
            name='thesis_d',
            field=models.CharField(blank=True, help_text='博士論文のタイトルを入力してください．', max_length=300, verbose_name='博士論文'),
        ),
        migrations.AddField(
            model_name='user',
            name='thesis_m',
            field=models.CharField(blank=True, help_text='修士論文のタイトルを入力してください．', max_length=300, verbose_name='修士論文'),
        ),
    ]
