# Generated by Django 3.2.5 on 2025-03-14 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20240127_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, default='', help_text='大学における学籍番号を記入してください．', max_length=8, validators=[django.core.validators.RegexValidator(message='7桁または8桁の半角英数字で入力してください．', regex='[0-9A-Z]{7,8}')], verbose_name='学籍番号'),
        ),
    ]
