# Generated by Django 2.0.13 on 2019-05-08 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('winner', models.TextField(help_text='受賞者全員を1名ずつ改行して記入してください．', max_length=200, verbose_name='受賞者リスト')),
                ('org', models.CharField(max_length=100, verbose_name='授与機関')),
                ('date', models.DateField(verbose_name='受賞年月日')),
                ('user', models.ManyToManyField(default=None, related_name='awarded_users', to=settings.AUTH_USER_MODEL, verbose_name='研究室内受賞者')),
            ],
        ),
    ]
