# Generated by Django 2.0.13 on 2021-01-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='winner',
            field=models.TextField(help_text='受賞者全員を1名ずつ改行して記入してください．賞のタイトルが英語の場合は，受賞者リストも英語で記入してください．', max_length=200, verbose_name='受賞者リスト'),
        ),
    ]
