version: "3"

services:
  web:
    restart: always
    build: .
    command: python ./web_site/manage.py runserver 0.0.0.0:9000
    hostname: "momi.nagaokaut.ac.jp"
    volumes:
      - .:/code
    ports:
      - 7777:9000
    container_name: django
