# Generated by Django 2.0.13 on 2019-09-22 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='キーワード')),
                ('weight', models.IntegerField(help_text='表示サイズを決めるウエイトを入力してください．', validators=[django.core.validators.MinValueValidator(0, message='0より小さい値は入力できません．'), django.core.validators.MaxValueValidator(9, message='9より大きい値は入力できません．')], verbose_name='ウエイト')),
            ],
        ),
    ]
