# Generated by Django 2.0.13 on 2019-10-06 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='weight',
            field=models.IntegerField(default=9, help_text='表示順を決める優先順位を入力してください(0〜9)．', validators=[django.core.validators.MinValueValidator(0, message='0より小さい値は入力できません．'), django.core.validators.MaxValueValidator(9, message='9より大きい値は入力できません．')], verbose_name='優先順位'),
            preserve_default=False,
        ),
    ]
