# Generated by Django 2.0.13 on 2019-10-06 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_internship_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAndA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='質問内容を入力してください．', verbose_name='質問内容')),
                ('answer', models.TextField(help_text='回答内容を入力してください．', verbose_name='回答内容')),
                ('weight', models.IntegerField(help_text='表示順を決める優先順位を入力してください(0〜9)．', validators=[django.core.validators.MinValueValidator(0, message='0より小さい値は入力できません．'), django.core.validators.MaxValueValidator(9, message='9より大きい値は入力できません．')], verbose_name='優先順位')),
            ],
        ),
    ]
