# Generated by Django 2.0.13 on 2019-10-07 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_auto_20191006_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='タイトル')),
                ('icon_tag', models.CharField(max_length=50, verbose_name='アイコンタグ')),
                ('description', models.TextField(verbose_name='説明')),
                ('weight', models.IntegerField(help_text='表示順を決める優先順位を入力してください(0-9)．', validators=[django.core.validators.MinValueValidator(0, message='0より小さい値は入力できません．'), django.core.validators.MaxValueValidator(9, message='9より大きい値は入力できません．')], verbose_name='ウエイト')),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='weight',
            field=models.IntegerField(help_text='表示サイズを決めるウエイトを入力してください(0-9)．', validators=[django.core.validators.MinValueValidator(0, message='0より小さい値は入力できません．'), django.core.validators.MaxValueValidator(9, message='9より大きい値は入力できません．')], verbose_name='ウエイト'),
        ),
    ]
