# Generated by Django 2.0.13 on 2019-10-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_auto_20191007_2322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Researches',
            new_name='Research',
        ),
    ]
