# Generated by Django 2.0.13 on 2019-11-07 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_auto_20191107_2246'),
        ('public', '0010_auto_20191007_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='年月日')),
                ('description', models.TextField(verbose_name='説明')),
                ('conference_title', models.ForeignKey(help_text='関連する画像があれば登録してください．', on_delete=django.db.models.deletion.CASCADE, related_name='information_picture', to='picture.Picture', verbose_name='画像')),
            ],
        ),
    ]
