# Generated by Django 2.0.13 on 2019-11-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_auto_20191107_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='picture',
            field=models.ForeignKey(help_text='関連する画像があれば登録してください．', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information_picture', to='picture.Picture', verbose_name='画像'),
        ),
    ]
