# Generated by Django 2.0.13 on 2019-11-24 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_auto_20191107_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='picture',
            field=models.ForeignKey(blank=True, help_text='関連する画像があれば登録してください．', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information_picture', to='picture.Picture', verbose_name='画像'),
        ),
    ]
