# Generated by Django 2.0.13 on 2021-01-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_auto_20191124_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='e_description',
            field=models.TextField(blank=True, verbose_name='説明(英語)'),
        ),
        migrations.AddField(
            model_name='research',
            name='e_title',
            field=models.CharField(blank=True, max_length=40, verbose_name='タイトル(英語)'),
        ),
    ]
