# Generated by Django 2.0.13 on 2021-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0015_auto_20210103_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='e_description',
            field=models.TextField(default=None, null=True, verbose_name='説明(英語)'),
        ),
    ]
