# Generated by Django 2.0.13 on 2019-09-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='web',
            field=models.BooleanField(default=False, help_text='ウェブサイトの一般公開ページで公開する場合はチェックを入れてください．', verbose_name='ウェブ公開'),
        ),
    ]
