# Generated by Django 2.0.13 on 2019-09-24 23:06

import django.core.validators
from django.db import migrations, models
import picture.models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_picture_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.ImageField(blank=True, help_text='写真のファイルを登録してください．', upload_to=picture.models.get_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'], message='JPEG，PNG，またはGIFファイルを添付してださい．')], verbose_name='添付ファイル'),
        ),
    ]
