# Generated by Django 2.0.13 on 2019-11-07 22:46

from django.db import migrations, models
import picture.models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20190924_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.ImageField(help_text='写真のファイルを登録してください．', upload_to=picture.models.get_upload_to, verbose_name='添付ファイル'),
        ),
    ]
