# Generated by Django 2.0.13 on 2020-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_auto_20191107_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='top_page',
            field=models.BooleanField(default=False, help_text='ウェブサイトの背景画像として公開する場合はチェックを入れてください.', verbose_name='背景画像'),
        ),
    ]
