# Generated by Django 2.0.13 on 2021-06-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0005_picture_top_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='category',
            field=models.IntegerField(choices=[(1, '研究室活動'), (6, '飯テロ'), (9, 'その他')], default=1, verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='picture',
            name='private',
            field=models.BooleanField(default=True, help_text='メンバー限定で公開する場合はチェックを入れてください．', verbose_name='メンバー限定公開'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='web',
            field=models.BooleanField(default=False, help_text='ウェブサイトの研究室ギャラリーで公開する場合はチェックを入れてください．', verbose_name='研究室ギャラリー公開'),
        ),
    ]
