# Generated by Django 2.0.13 on 2021-06-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0006_auto_20210624_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='category',
            field=models.IntegerField(choices=[(1, '研究室イベント'), (2, '研究室紹介'), (6, '飯テロ'), (9, 'その他')], default=1, verbose_name='カテゴリ'),
        ),
    ]
