def latex2escape_char(string):
    """LaTeXを拡張文字に変換"""
    
    # 記号の変換
    string = string.replace('{\&}', '&')
    string = string.replace('{\{}', '{')
    string = string.replace('{\}}', '}')
    string = string.replace('{\$}', '$')
    string = string.replace('{\_}', '_')
    string = string.replace('{\%}', '%')
    string = string.replace('{\\"}', '"')
    
    # アキュート・アクセント
    string = string.replace("\\'{a}", 'á')
    string = string.replace("\\'{c}", 'ć')
    string = string.replace("\\'{e}", 'é')
    string = string.replace("\\'{g}", 'ǵ')
    string = string.replace("\\'{\i}", 'í')
    string = string.replace("\\'{k}", 'ḱ')
    string = string.replace("\\'{l}", 'ĺ')
    string = string.replace("\\'{m}", 'ḿ')
    string = string.replace("\\'{n}", 'ń')
    string = string.replace("\\'{o}", 'ó')
    string = string.replace("\\'{p}", 'ṕ')
    string = string.replace("\\'{r}", 'ŕ')
    string = string.replace("\\'{s}", 'ś')
    string = string.replace("\\'{u}", 'ú')
    string = string.replace("\\'{w}", 'ẃ')
    string = string.replace("\\'{y}", 'ý')
    string = string.replace("\\'{z}", 'ź')
    string = string.replace("\\'{A}", 'Á')
    string = string.replace("\\'{C}", 'Ć')
    string = string.replace("\\'{E}", 'É')
    string = string.replace("\\'{G}", 'Ǵ')
    string = string.replace("\\'{I}", 'Í')
    string = string.replace("\\'{K}", 'Ḱ')
    string = string.replace("\\'{L}", 'Ĺ')
    string = string.replace("\\'{M}", 'Ḿ')
    string = string.replace("\\'{N}", 'Ń')
    string = string.replace("\\'{O}", 'Ó')
    string = string.replace("\\'{P}", 'Ṕ')
    string = string.replace("\\'{R}", 'Ŕ')
    string = string.replace("\\'{S}", 'Ś')
    string = string.replace("\\'{U}", 'Ú')
    string = string.replace("\\'{W}", 'Ẃ')
    string = string.replace("\\'{Y}", 'Ý')
    string = string.replace("\\'{Z}", 'Ź')
    
    # ダブルアキュート
    string = string.replace('\H{o}', 'ő')
    string = string.replace('\H{u}', 'ű')
    string = string.replace('\H{O}', 'Ő')
    string = string.replace('\H{U}', 'Ű')
    
    # グレーブ・アクセント
    string = string.replace('\`{a}', 'à')
    string = string.replace('\`{e}', 'è')
    string = string.replace('\`{\i}', 'ì')
    string = string.replace('\`{n}', 'ǹ')
    string = string.replace('\`{o}', 'ò')
    string = string.replace('\`{u}', 'ù')
    string = string.replace('\`{w}', 'ẁ')
    string = string.replace('\`{y}', 'ỳ')
    string = string.replace('\`{A}', 'À')
    string = string.replace('\`{E}', 'È')
    string = string.replace('\`{I}', 'Ì')
    string = string.replace('\`{N}', 'Ǹ')
    string = string.replace('\`{O}', 'Ò')
    string = string.replace('\`{U}', 'Ù')
    string = string.replace('\`{W}', 'Ẁ')
    string = string.replace('\`{Y}', 'Ỳ')
    
    # ブレーヴェ
    string = string.replace('\\u{a}', 'ă')
    string = string.replace('\\u{e}', 'ĕ')
    string = string.replace('\\u{g}', 'ğ')
    string = string.replace('\\u{\i}', 'ĭ')
    string = string.replace('\\u{o}', 'ŏ')
    string = string.replace('\\u{u}', 'ŭ')
    string = string.replace('\\u{A}', 'Ă')
    string = string.replace('\\u{E}', 'Ĕ')
    string = string.replace('\\u{G}', 'Ğ')
    string = string.replace('\\u{I}', 'Ĭ')
    string = string.replace('\\u{O}', 'Ŏ')
    string = string.replace('\\u{U}', 'Ŭ')
    
    # ハーチェク
    string = string.replace('\\v{a}', 'ǎ')
    string = string.replace('\\v{c}', 'č')
    string = string.replace('\\v{e}', 'ě')
    string = string.replace('\\v{g}', 'ǧ')
    string = string.replace('\\v{h}', 'ȟ')
    string = string.replace('\\v{k}', 'ǩ')
    string = string.replace('\\v{n}', 'ň')
    string = string.replace('\\v{o}', 'ǒ')
    string = string.replace('\\v{r}', 'ř')
    string = string.replace('\\v{s}', 'š')
    string = string.replace('\\v{u}', 'ǔ')
    string = string.replace('\\v{z}', 'ž')
    string = string.replace('\\v{A}', 'Ǎ')
    string = string.replace('\\v{C}', 'Č')
    string = string.replace('\\v{D}', 'Ď')
    string = string.replace('\\v{E}', 'Ě')
    string = string.replace('\\v{G}', 'Ǧ')
    string = string.replace('\\v{H}', 'Ȟ')
    string = string.replace('\\v{K}', 'Ǩ')
    string = string.replace('\\v{I}', 'Ǐ')
    string = string.replace('\\v{N}', 'Ň')
    string = string.replace('\\v{O}', 'Ǒ')
    string = string.replace('\\v{R}', 'Ř')
    string = string.replace('\\v{S}', 'Š')
    string = string.replace('\\v{T}', 'Ť')
    string = string.replace('\\v{U}', 'Ǔ')
    string = string.replace('\\v{Z}', 'Ž')
    
    # セディーユ
    string = string.replace('\c{c}', 'ç')
    string = string.replace('\c{d}', 'ḑ')
    string = string.replace('\c{e}', 'ȩ')
    string = string.replace('\c{h}', 'ḩ')
    string = string.replace('\c{k}', 'ķ')
    string = string.replace('\c{l}', 'ļ')
    string = string.replace('\c{n}', 'ņ')
    string = string.replace('\c{r}', 'ŗ')
    string = string.replace('\c{s}', 'ş')
    string = string.replace('\c{t}', 'ţ')
    string = string.replace('\c{C}', 'Ç')
    string = string.replace('\c{D}', 'Ḑ')
    string = string.replace('\c{E}', 'Ȩ')
    string = string.replace('\c{G}', 'Ģ')
    string = string.replace('\c{H}', 'Ḩ')
    string = string.replace('\c{K}', 'Ķ')
    string = string.replace('\c{L}', 'Ļ')
    string = string.replace('\c{N}', 'Ņ')
    string = string.replace('\c{R}', 'Ŗ')
    string = string.replace('\c{S}', 'Ş')
    string = string.replace('\c{T}', 'Ţ')
    
    # サーカムフレックス
    string = string.replace('\^{a}', 'â')
    string = string.replace('\^{c}', 'ĉ')
    string = string.replace('\^{e}', 'ê')
    string = string.replace('\^{g}', 'ĝ')
    string = string.replace('\^{h}', 'ĥ')
    string = string.replace('\^{\i}', 'î')
    string = string.replace('\^{\j}', 'ĵ')
    string = string.replace('\^{o}', 'ô')
    string = string.replace('\^{s}', 'ŝ')
    string = string.replace('\^{u}', 'û')
    string = string.replace('\^{w}', 'ŵ')
    string = string.replace('\^{y}', 'ŷ')
    string = string.replace('\^{z}', 'ẑ')
    string = string.replace('\^{A}', 'Â')
    string = string.replace('\^{C}', 'Ĉ')
    string = string.replace('\^{E}', 'Ê')
    string = string.replace('\^{G}', 'Ĝ')
    string = string.replace('\^{H}', 'Ĥ')
    string = string.replace('\^{I}', 'Î')
    string = string.replace('\^{J}', 'Ĵ')
    string = string.replace('\^{O}', 'Ô')
    string = string.replace('\^{S}', 'Ŝ')
    string = string.replace('\^{U}', 'Û')
    string = string.replace('\^{W}', 'Ŵ')
    string = string.replace('\^{Y}', 'Ŷ')
    string = string.replace('\^{Z}', 'Ẑ')
    
    # トレマ，ウムラウト
    string = string.replace('\\"{a}', 'ä')
    string = string.replace('\\"{e}', 'ë')
    string = string.replace('\\"{h}', 'ḧ')
    string = string.replace('\\"{\i}', 'ï')
    string = string.replace('\\"{o}', 'ö')
    string = string.replace('\\"{u}', 'ü')
    string = string.replace('\\"{w}', 'ẅ')
    string = string.replace('\\"{x}', 'ẍ')
    string = string.replace('\\"{y}', 'ÿ')
    string = string.replace('\\"{A}', 'Ä')
    string = string.replace('\\"{E}', 'Ë')
    string = string.replace('\\"{H}', 'Ḧ')
    string = string.replace('\\"{I}', 'Ï')
    string = string.replace('\\"{O}', 'Ö')
    string = string.replace('\\"{U}', 'Ü')
    string = string.replace('\\"{W}', 'Ẅ')
    string = string.replace('\\"{X}', 'Ẍ')
    string = string.replace('\\"{Y}', 'Ÿ')
    
    # チルダ
    string = string.replace('\~{a}', 'ã')
    string = string.replace('\~{e}', 'ẽ')
    string = string.replace('\~{\i}', 'ĩ')
    string = string.replace('\~{n}', 'ñ')
    string = string.replace('\~{o}', 'õ')
    string = string.replace('\~{u}', 'ũ')
    string = string.replace('\~{v}', 'ṽ')
    string = string.replace('\~{y}', 'ỹ')
    string = string.replace('\~{A}', 'Ã')
    string = string.replace('\~{E}', 'Ẽ')
    string = string.replace('\~{I}', 'Ĩ')
    string = string.replace('\~{N}', 'Ñ')
    string = string.replace('\~{O}', 'Õ')
    string = string.replace('\~{U}', 'Ũ')
    string = string.replace('\~{V}', 'Ṽ')
    string = string.replace('\~{Y}', 'Ỹ')
    
    # 上付きドット符号
    string = string.replace('\.{a}', 'ȧ')
    string = string.replace('\.{b}', 'ḃ')
    string = string.replace('\.{c}', 'ċ')
    string = string.replace('\.{d}', 'ḋ')
    string = string.replace('\.{e}', 'ė')
    string = string.replace('\.{f}', 'ḟ')
    string = string.replace('\.{g}', 'ġ')
    string = string.replace('\.{h}', 'ḣ')
    string = string.replace('\.{m}', 'ṁ')
    string = string.replace('\.{n}', 'ṅ')
    string = string.replace('\.{o}', 'ȯ')
    string = string.replace('\.{p}', 'ṗ')
    string = string.replace('\.{r}', 'ṙ')
    string = string.replace('\.{s}', 'ṡ')
    string = string.replace('\.{t}', 'ṫ')
    string = string.replace('\.{w}', 'ẇ')
    string = string.replace('\.{x}', 'ẋ')
    string = string.replace('\.{y}', 'ẏ')
    string = string.replace('\.{z}', 'ż')
    string = string.replace('\.{A}', 'Ȧ')
    string = string.replace('\.{B}', 'Ḃ')
    string = string.replace('\.{C}', 'Ċ')
    string = string.replace('\.{D}', 'Ḋ')
    string = string.replace('\.{E}', 'Ė')
    string = string.replace('\.{F}', 'Ḟ')
    string = string.replace('\.{G}', 'Ġ')
    string = string.replace('\.{H}', 'Ḣ')
    string = string.replace('\.{I}', 'İ')
    string = string.replace('\.{M}', 'Ṁ')
    string = string.replace('\.{N}', 'Ṅ')
    string = string.replace('\.{O}', 'Ȯ')
    string = string.replace('\.{P}', 'Ṗ')
    string = string.replace('\.{R}', 'Ṙ')
    string = string.replace('\.{S}', 'Ṡ')
    string = string.replace('\.{T}', 'Ṫ')
    string = string.replace('\.{W}', 'Ẇ')
    string = string.replace('\.{X}', 'Ẋ')
    string = string.replace('\.{Y}', 'Ẏ')
    string = string.replace('\.{Z}', 'Ż')
    
    # 下付きドット記号
    string = string.replace('\d{a}', 'ạ')
    string = string.replace('\d{b}', 'ḅ')
    string = string.replace('\d{d}', 'ḍ')
    string = string.replace('\d{e}', 'ẹ')
    string = string.replace('\d{h}', 'ḥ')
    string = string.replace('\d{\i}', 'ị')
    string = string.replace('\d{k}', 'ḳ')
    string = string.replace('\d{l}', 'ḷ')
    string = string.replace('\d{m}', 'ṃ')
    string = string.replace('\d{n}', 'ṇ')
    string = string.replace('\d{o}', 'ọ')
    string = string.replace('\d{r}', 'ṛ')
    string = string.replace('\d{s}', 'ṣ')
    string = string.replace('\d{t}', 'ṭ')
    string = string.replace('\d{u}', 'ụ')
    string = string.replace('\d{v}', 'ṿ')
    string = string.replace('\d{w}', 'ẉ')
    string = string.replace('\d{y}', 'ỵ')
    string = string.replace('\d{z}', 'ẓ')
    string = string.replace('\d{A}', 'Ạ')
    string = string.replace('\d{B}', 'Ḅ')
    string = string.replace('\d{D}', 'Ḍ')
    string = string.replace('\d{E}', 'Ẹ')
    string = string.replace('\d{H}', 'Ḥ')
    string = string.replace('\d{I}', 'Ị')
    string = string.replace('\d{K}', 'Ḳ')
    string = string.replace('\d{L}', 'Ḷ')
    string = string.replace('\d{M}', 'Ṃ')
    string = string.replace('\d{N}', 'Ṇ')
    string = string.replace('\d{O}', 'Ọ')
    string = string.replace('\d{R}', 'Ṛ')
    string = string.replace('\d{S}', 'Ṣ')
    string = string.replace('\d{T}', 'Ṭ')
    string = string.replace('\d{U}', 'Ụ')
    string = string.replace('\d{V}', 'Ṿ')
    string = string.replace('\d{W}', 'Ẉ')
    string = string.replace('\d{Y}', 'Ỵ')
    string = string.replace('\d{Z}', 'Ẓ')
    
    # 上付きマクロン
    string = string.replace('\={a}', 'ā')
    string = string.replace('\={e}', 'ē')
    string = string.replace('\={g}', 'ḡ')
    string = string.replace('\={\i}', 'ī')
    string = string.replace('\={o}', 'ō')
    string = string.replace('\={u}', 'ū')
    string = string.replace('\={y}', 'ȳ')
    string = string.replace('\={A}', 'Ā')
    string = string.replace('\={E}', 'Ē')
    string = string.replace('\={G}', 'Ḡ')
    string = string.replace('\={I}', 'Ī')
    string = string.replace('\={O}', 'Ō')
    string = string.replace('\={U}', 'Ū')
    string = string.replace('\={Y}', 'Ȳ')
    
    # 下付きマクロン
    string = string.replace('\\b{b}', 'ḇ')
    string = string.replace('\\b{d}', 'ḏ')
    string = string.replace('\\b{k}', 'ḵ')
    string = string.replace('\\b{l}', 'ḻ')
    string = string.replace('\\b{n}', 'ṉ')
    string = string.replace('\\b{r}', 'ṟ')
    string = string.replace('\\b{t}', 'ṯ')
    string = string.replace('\\b{z}', 'ẕ')
    string = string.replace('\\b{B}', 'Ḇ')
    string = string.replace('\\b{D}', 'Ḏ')
    string = string.replace('\\b{K}', 'Ḵ')
    string = string.replace('\\b{L}', 'Ḻ')
    string = string.replace('\\b{N}', 'Ṉ')
    string = string.replace('\\b{R}', 'Ṟ')
    string = string.replace('\\b{T}', 'Ṯ')
    string = string.replace('\\b{Z}', 'Ẕ')
    
    # リング符号
    string = string.replace('\\aa', 'å')
    string = string.replace('\\AA', 'Å')
    string = string.replace('\\r{u}', 'ů')
    string = string.replace('\\{U}', 'Ů')
    
    # その他
    string = string.replace('{\ss}', 'ß')
    string = string.replace('{\AE}', 'Æ')
    string = string.replace('{\\ae}', 'æ')
    string = string.replace('{\OE}', 'Œ')
    string = string.replace('{\oe}', 'œ')
    string = string.replace('{\L}', 'Ł')
    string = string.replace('{\l}', 'ł')
    string = string.replace('{\O}', 'Ø')
    string = string.replace('{\o}', 'ø')
    string = string.replace('{\DJ}', 'Đ')
    string = string.replace('{\dj}', 'đ')
    string = string.replace('{\DH}', 'Đ')
    string = string.replace('{\dh}', 'ð')
    string = string.replace('{\\NG}', 'Ŋ')
    string = string.replace('{\\ng}', 'ŋ')
    string = string.replace('{\TH}', 'Þ')
    string = string.replace('{\\th}', 'þ')
    
    return string


def escape_char2latex(string):
    """LaTeXで表示可能な文字に変換"""
    if string.count('$') < 2:  # $の出現が2個以上の場合は，LaTeX数式と判定して，記号をエスケープしない．
        # 記号の変換
        string = string.replace('$', '{\$}')
        string = string.replace('_', '{\_}')
        string = string.replace('{', '{\{}')
        string = string.replace('}', '{\}}')
    string = string.replace('&', '{\&}')
    string = string.replace('%', '{\%}')
    string = string.replace('"', '{\\"}')
    
    # アキュート・アクセント
    string = string.replace('á', "\\'{a}")
    string = string.replace('ć', "\\'{c}")
    string = string.replace('é', "\\'{e}")
    string = string.replace('ǵ', "\\'{g}")
    string = string.replace('í', "\\'{\i}")
    string = string.replace('ḱ', "\\'{k}")
    string = string.replace('ĺ', "\\'{l}")
    string = string.replace('ḿ', "\\'{m}")
    string = string.replace('ń', "\\'{n}")
    string = string.replace('ó', "\\'{o}")
    string = string.replace('ṕ', "\\'{p}")
    string = string.replace('ŕ', "\\'{r}")
    string = string.replace('ś', "\\'{s}")
    string = string.replace('ú', "\\'{u}")
    string = string.replace('ẃ', "\\'{w}")
    string = string.replace('ý', "\\'{y}")
    string = string.replace('ź', "\\'{z}")
    string = string.replace('Á', "\\'{A}")
    string = string.replace('Ć', "\\'{C}")
    string = string.replace('É', "\\'{E}")
    string = string.replace('Ǵ', "\\'{G}")
    string = string.replace('Í', "\\'{I}")
    string = string.replace('Ḱ', "\\'{K}")
    string = string.replace('Ĺ', "\\'{L}")
    string = string.replace('Ḿ', "\\'{M}")
    string = string.replace('Ń', "\\'{N}")
    string = string.replace('Ó', "\\'{O}")
    string = string.replace('Ṕ', "\\'{P}")
    string = string.replace('Ŕ', "\\'{R}")
    string = string.replace('Ś', "\\'{S}")
    string = string.replace('Ú', "\\'{U}")
    string = string.replace('Ẃ', "\\'{W}")
    string = string.replace('Ý', "\\'{Y}")
    string = string.replace('Ź', "\\'{Z}")
    
    # ダブルアキュート
    string = string.replace('ő', '\H{o}')
    string = string.replace('ű', '\H{u}')
    string = string.replace('Ő', '\H{O}')
    string = string.replace('Ű', '\H{U}')
    
    # グレーブ・アクセント
    string = string.replace('à', '\`{a}')
    string = string.replace('è', '\`{e}')
    string = string.replace('ì', '\`{\i}')
    string = string.replace('ǹ', '\`{n}')
    string = string.replace('ò', '\`{o}')
    string = string.replace('ù', '\`{u}')
    string = string.replace('ẁ', '\`{w}')
    string = string.replace('ỳ', '\`{y}')
    string = string.replace('À', '\`{A}')
    string = string.replace('È', '\`{E}')
    string = string.replace('Ì', '\`{I}')
    string = string.replace('Ǹ', '\`{N}')
    string = string.replace('Ò', '\`{O}')
    string = string.replace('Ù', '\`{U}')
    string = string.replace('Ẁ', '\`{W}')
    string = string.replace('Ỳ', '\`{Y}')
    
    # ブレーヴェ
    string = string.replace('ă', '\\u{a}')
    string = string.replace('ĕ', '\\u{e}')
    string = string.replace('ğ', '\\u{g}')
    string = string.replace('ĭ', '\\u{\i}')
    string = string.replace('ŏ', '\\u{o}')
    string = string.replace('ŭ', '\\u{u}')
    string = string.replace('Ă', '\\u{A}')
    string = string.replace('Ĕ', '\\u{E}')
    string = string.replace('Ğ', '\\u{G}')
    string = string.replace('Ĭ', '\\u{I}')
    string = string.replace('Ŏ', '\\u{O}')
    string = string.replace('Ŭ', '\\u{U}')
    
    # ハーチェク
    string = string.replace('ǎ', '\\v{a}')
    string = string.replace('č', '\\v{c}')
    string = string.replace('ě', '\\v{e}')
    string = string.replace('ǧ', '\\v{g}')
    string = string.replace('ȟ', '\\v{h}')
    string = string.replace('ǩ', '\\v{k}')
    string = string.replace('ň', '\\v{n}')
    string = string.replace('ǒ', '\\v{o}')
    string = string.replace('ř', '\\v{r}')
    string = string.replace('š', '\\v{s}')
    string = string.replace('ǔ', '\\v{u}')
    string = string.replace('ž', '\\v{z}')
    string = string.replace('Ǎ', '\\v{A}')
    string = string.replace('Č', '\\v{C}')
    string = string.replace('Ď', '\\v{D}')
    string = string.replace('Ě', '\\v{E}')
    string = string.replace('Ǧ', '\\v{G}')
    string = string.replace('Ȟ', '\\v{H}')
    string = string.replace('Ǩ', '\\v{K}')
    string = string.replace('Ǐ', '\\v{I}')
    string = string.replace('Ň', '\\v{N}')
    string = string.replace('Ǒ', '\\v{O}')
    string = string.replace('Ř', '\\v{R}')
    string = string.replace('Š', '\\v{S}')
    string = string.replace('Ť', '\\v{T}')
    string = string.replace('Ǔ', '\\v{U}')
    string = string.replace('Ž', '\\v{Z}')
    
    # セディーユ
    string = string.replace('ç', '\c{c}')
    string = string.replace('ḑ', '\c{d}')
    string = string.replace('ȩ', '\c{e}')
    string = string.replace('ḩ', '\c{h}')
    string = string.replace('ķ', '\c{k}')
    string = string.replace('ļ', '\c{l}')
    string = string.replace('ņ', '\c{n}')
    string = string.replace('ŗ', '\c{r}')
    string = string.replace('ş', '\c{s}')
    string = string.replace('ţ', '\c{t}')
    string = string.replace('Ç', '\c{C}')
    string = string.replace('Ḑ', '\c{D}')
    string = string.replace('Ȩ', '\c{E}')
    string = string.replace('Ģ', '\c{G}')
    string = string.replace('Ḩ', '\c{H}')
    string = string.replace('Ķ', '\c{K}')
    string = string.replace('Ļ', '\c{L}')
    string = string.replace('Ņ', '\c{N}')
    string = string.replace('Ŗ', '\c{R}')
    string = string.replace('Ş', '\c{S}')
    string = string.replace('Ţ', '\c{T}')
    
    # サーカムフレックス
    string = string.replace('â', '\^{a}')
    string = string.replace('ĉ', '\^{c}')
    string = string.replace('ê', '\^{e}')
    string = string.replace('ĝ', '\^{g}')
    string = string.replace('ĥ', '\^{h}')
    string = string.replace('î', '\^{\i}')
    string = string.replace('ĵ', '\^{\j}')
    string = string.replace('ô', '\^{o}')
    string = string.replace('ŝ', '\^{s}')
    string = string.replace('û', '\^{u}')
    string = string.replace('ŵ', '\^{w}')
    string = string.replace('ŷ', '\^{y}')
    string = string.replace('ẑ', '\^{z}')
    string = string.replace('Â', '\^{A}')
    string = string.replace('Ĉ', '\^{C}')
    string = string.replace('Ê', '\^{E}')
    string = string.replace('Ĝ', '\^{G}')
    string = string.replace('Ĥ', '\^{H}')
    string = string.replace('Î', '\^{I}')
    string = string.replace('Ĵ', '\^{J}')
    string = string.replace('Ô', '\^{O}')
    string = string.replace('Ŝ', '\^{S}')
    string = string.replace('Û', '\^{U}')
    string = string.replace('Ŵ', '\^{W}')
    string = string.replace('Ŷ', '\^{Y}')
    string = string.replace('Ẑ', '\^{Z}')
    
    # トレマ，ウムラウト
    string = string.replace('ä', '\\"{a}')
    string = string.replace('ë', '\\"{e}')
    string = string.replace('ḧ', '\\"{h}')
    string = string.replace('ï', '\\"{\i}')
    string = string.replace('ö', '\\"{o}')
    string = string.replace('ü', '\\"{u}')
    string = string.replace('ẅ', '\\"{w}')
    string = string.replace('ẍ', '\\"{x}')
    string = string.replace('ÿ', '\\"{y}')
    string = string.replace('Ä', '\\"{A}')
    string = string.replace('Ë', '\\"{E}')
    string = string.replace('Ḧ', '\\"{H}')
    string = string.replace('Ï', '\\"{I}')
    string = string.replace('Ö', '\\"{O}')
    string = string.replace('Ü', '\\"{U}')
    string = string.replace('Ẅ', '\\"{W}')
    string = string.replace('Ẍ', '\\"{X}')
    string = string.replace('Ÿ', '\\"{Y}')
    
    # チルダ
    string = string.replace('ã', '\~{a}')
    string = string.replace('ẽ', '\~{e}')
    string = string.replace('ĩ', '\~{\i}')
    string = string.replace('ñ', '\~{n}')
    string = string.replace('õ', '\~{o}')
    string = string.replace('ũ', '\~{u}')
    string = string.replace('ṽ', '\~{v}')
    string = string.replace('ỹ', '\~{y}')
    string = string.replace('Ã', '\~{A}')
    string = string.replace('Ẽ', '\~{E}')
    string = string.replace('Ĩ', '\~{I}')
    string = string.replace('Ñ', '\~{N}')
    string = string.replace('Õ', '\~{O}')
    string = string.replace('Ũ', '\~{U}')
    string = string.replace('Ṽ', '\~{V}')
    string = string.replace('Ỹ', '\~{Y}')
    
    # 上付きドット符号
    string = string.replace('ȧ', '\.{a}')
    string = string.replace('ḃ', '\.{b}')
    string = string.replace('ċ', '\.{c}')
    string = string.replace('ḋ', '\.{d}')
    string = string.replace('ė', '\.{e}')
    string = string.replace('ḟ', '\.{f}')
    string = string.replace('ġ', '\.{g}')
    string = string.replace('ḣ', '\.{h}')
    string = string.replace('ṁ', '\.{m}')
    string = string.replace('ṅ', '\.{n}')
    string = string.replace('ȯ', '\.{o}')
    string = string.replace('ṗ', '\.{p}')
    string = string.replace('ṙ', '\.{r}')
    string = string.replace('ṡ', '\.{s}')
    string = string.replace('ṫ', '\.{t}')
    string = string.replace('ẇ', '\.{w}')
    string = string.replace('ẋ', '\.{x}')
    string = string.replace('ẏ', '\.{y}')
    string = string.replace('ż', '\.{z}')
    string = string.replace('Ȧ', '\.{A}')
    string = string.replace('Ḃ', '\.{B}')
    string = string.replace('Ċ', '\.{C}')
    string = string.replace('Ḋ', '\.{D}')
    string = string.replace('Ė', '\.{E}')
    string = string.replace('Ḟ', '\.{F}')
    string = string.replace('Ġ', '\.{G}')
    string = string.replace('Ḣ', '\.{H}')
    string = string.replace('İ', '\.{I}')
    string = string.replace('Ṁ', '\.{M}')
    string = string.replace('Ṅ', '\.{N}')
    string = string.replace('Ȯ', '\.{O}')
    string = string.replace('Ṗ', '\.{P}')
    string = string.replace('Ṙ', '\.{R}')
    string = string.replace('Ṡ', '\.{S}')
    string = string.replace('Ṫ', '\.{T}')
    string = string.replace('Ẇ', '\.{W}')
    string = string.replace('Ẋ', '\.{X}')
    string = string.replace('Ẏ', '\.{Y}')
    string = string.replace('Ż', '\.{Z}')
    
    # 下付きドット記号
    string = string.replace('ạ', '\d{a}')
    string = string.replace('ḅ', '\d{b}')
    string = string.replace('ḍ', '\d{d}')
    string = string.replace('ẹ', '\d{e}')
    string = string.replace('ḥ', '\d{h}')
    string = string.replace('ị', '\d{\i}')
    string = string.replace('ḳ', '\d{k}')
    string = string.replace('ḷ', '\d{l}')
    string = string.replace('ṃ', '\d{m}')
    string = string.replace('ṇ', '\d{n}')
    string = string.replace('ọ', '\d{o}')
    string = string.replace('ṛ', '\d{r}')
    string = string.replace('ṣ', '\d{s}')
    string = string.replace('ṭ', '\d{t}')
    string = string.replace('ụ', '\d{u}')
    string = string.replace('ṿ', '\d{v}')
    string = string.replace('ẉ', '\d{w}')
    string = string.replace('ỵ', '\d{y}')
    string = string.replace('ẓ', '\d{z}')
    string = string.replace('Ạ', '\d{A}')
    string = string.replace('Ḅ', '\d{B}')
    string = string.replace('Ḍ', '\d{D}')
    string = string.replace('Ẹ', '\d{E}')
    string = string.replace('Ḥ', '\d{H}')
    string = string.replace('Ị', '\d{I}')
    string = string.replace('Ḳ', '\d{K}')
    string = string.replace('Ḷ', '\d{L}')
    string = string.replace('Ṃ', '\d{M}')
    string = string.replace('Ṇ', '\d{N}')
    string = string.replace('Ọ', '\d{O}')
    string = string.replace('Ṛ', '\d{R}')
    string = string.replace('Ṣ', '\d{S}')
    string = string.replace('Ṭ', '\d{T}')
    string = string.replace('Ụ', '\d{U}')
    string = string.replace('Ṿ', '\d{V}')
    string = string.replace('Ẉ', '\d{W}')
    string = string.replace('Ỵ', '\d{Y}')
    string = string.replace('Ẓ', '\d{Z}')
    
    # 上付きマクロン
    string = string.replace('ā', '\={a}')
    string = string.replace('ē', '\={e}')
    string = string.replace('ḡ', '\={g}')
    string = string.replace('ī', '\={\i}')
    string = string.replace('ō', '\={o}')
    string = string.replace('ū', '\={u}')
    string = string.replace('ȳ', '\={y}')
    string = string.replace('Ā', '\={A}')
    string = string.replace('Ē', '\={E}')
    string = string.replace('Ḡ', '\={G}')
    string = string.replace('Ī', '\={I}')
    string = string.replace('Ō', '\={O}')
    string = string.replace('Ū', '\={U}')
    string = string.replace('Ȳ', '\={Y}')
    
    # 下付きマクロン
    string = string.replace('ḇ', '\\b{b}')
    string = string.replace('ḏ', '\\b{d}')
    string = string.replace('ḵ', '\\b{k}')
    string = string.replace('ḻ', '\\b{l}')
    string = string.replace('ṉ', '\\b{n}')
    string = string.replace('ṟ', '\\b{r}')
    string = string.replace('ṯ', '\\b{t}')
    string = string.replace('ẕ', '\\b{z}')
    string = string.replace('Ḇ', '\\b{B}')
    string = string.replace('Ḏ', '\\b{D}')
    string = string.replace('Ḵ', '\\b{K}')
    string = string.replace('Ḻ', '\\b{L}')
    string = string.replace('Ṉ', '\\b{N}')
    string = string.replace('Ṟ', '\\b{R}')
    string = string.replace('Ṯ', '\\b{T}')
    string = string.replace('Ẕ', '\\b{Z}')
    
    # リング符号
    string = string.replace('å', '\\aa')
    string = string.replace('Å', '\\AA')
    string = string.replace('ů', '\\r{u}')
    string = string.replace('Ů', '\\{U}')
    
    # その他
    string = string.replace('ß', '{\ss}')
    string = string.replace('Æ', '{\AE}')
    string = string.replace('æ', '{\\ae}')
    string = string.replace('Œ', '{\OE}')
    string = string.replace('œ', '{\oe}')
    string = string.replace('Ł', '{\L}')
    string = string.replace('ł', '{\l}')
    string = string.replace('Ø', '{\O}')
    string = string.replace('ø', '{\o}')
    string = string.replace('Đ', '{\DJ}')
    string = string.replace('đ', '{\dj}')
    string = string.replace('Đ', '{\DH}')
    string = string.replace('ð', '{\dh}')
    string = string.replace('Ŋ', '{\\NG}')
    string = string.replace('ŋ', '{\\ng}')
    string = string.replace('Þ', '{\TH}')
    string = string.replace('þ', '{\\th}')
    
    return string


def escape_char2ascii(string):
    """LaTeXで表示可能な文字に変換"""

    # アキュート・アクセント
    string = string.replace('á', "a")
    string = string.replace('ć', "c")
    string = string.replace('é', "e")
    string = string.replace('ǵ', "g")
    string = string.replace('í', "i")
    string = string.replace('ḱ', "k")
    string = string.replace('ĺ', "l")
    string = string.replace('ḿ', "m")
    string = string.replace('ń', "n")
    string = string.replace('ó', "o")
    string = string.replace('ṕ', "p")
    string = string.replace('ŕ', "r")
    string = string.replace('ś', "s")
    string = string.replace('ú', "u")
    string = string.replace('ẃ', "w")
    string = string.replace('ý', "y")
    string = string.replace('ź', "z")
    string = string.replace('Á', "A")
    string = string.replace('Ć', "C")
    string = string.replace('É', "E")
    string = string.replace('Ǵ', "G")
    string = string.replace('Í', "I")
    string = string.replace('Ḱ', "K")
    string = string.replace('Ĺ', "L")
    string = string.replace('Ḿ', "M")
    string = string.replace('Ń', "N")
    string = string.replace('Ó', "O")
    string = string.replace('Ṕ', "P")
    string = string.replace('Ŕ', "R")
    string = string.replace('Ś', "S")
    string = string.replace('Ú', "U")
    string = string.replace('Ẃ', "W")
    string = string.replace('Ý', "Y")
    string = string.replace('Ź', "Z")

    # ダブルアキュート
    string = string.replace('ő', 'o')
    string = string.replace('ű', 'u')
    string = string.replace('Ő', 'O')
    string = string.replace('Ű', 'U')

    # グレーブ・アクセント
    string = string.replace('à', 'a')
    string = string.replace('è', 'e')
    string = string.replace('ì', 'i')
    string = string.replace('ǹ', 'n')
    string = string.replace('ò', 'o')
    string = string.replace('ù', 'u')
    string = string.replace('ẁ', 'w')
    string = string.replace('ỳ', 'y')
    string = string.replace('À', 'A')
    string = string.replace('È', 'E')
    string = string.replace('Ì', 'I')
    string = string.replace('Ǹ', 'N')
    string = string.replace('Ò', 'O')
    string = string.replace('Ù', 'U')
    string = string.replace('Ẁ', 'W')
    string = string.replace('Ỳ', 'Y')

    # ブレーヴェ
    string = string.replace('ă', 'a')
    string = string.replace('ĕ', 'e')
    string = string.replace('ğ', 'g')
    string = string.replace('ĭ', 'i')
    string = string.replace('ŏ', 'o')
    string = string.replace('ŭ', 'u')
    string = string.replace('Ă', 'A')
    string = string.replace('Ĕ', 'E')
    string = string.replace('Ğ', 'G')
    string = string.replace('Ĭ', 'I')
    string = string.replace('Ŏ', 'O')
    string = string.replace('Ŭ', 'U')

    # ハーチェク
    string = string.replace('ǎ', 'a')
    string = string.replace('č', 'c')
    string = string.replace('ě', 'e')
    string = string.replace('ǧ', 'g')
    string = string.replace('ȟ', 'h')
    string = string.replace('ǩ', 'k')
    string = string.replace('ň', 'n')
    string = string.replace('ǒ', 'o')
    string = string.replace('ř', 'r')
    string = string.replace('š', 's')
    string = string.replace('ǔ', 'u')
    string = string.replace('ž', 'z')
    string = string.replace('Ǎ', 'A')
    string = string.replace('Č', 'C')
    string = string.replace('Ď', 'D')
    string = string.replace('Ě', 'E')
    string = string.replace('Ǧ', 'G')
    string = string.replace('Ȟ', 'H')
    string = string.replace('Ǩ', 'K')
    string = string.replace('Ǐ', 'I')
    string = string.replace('Ň', 'N')
    string = string.replace('Ǒ', 'O')
    string = string.replace('Ř', 'R')
    string = string.replace('Š', 'S')
    string = string.replace('Ť', 'T')
    string = string.replace('Ǔ', 'U')
    string = string.replace('Ž', 'Z')

    # セディーユ
    string = string.replace('ç', 'c')
    string = string.replace('ḑ', 'd')
    string = string.replace('ȩ', 'e')
    string = string.replace('ḩ', 'h')
    string = string.replace('ķ', 'k')
    string = string.replace('ļ', 'l')
    string = string.replace('ņ', 'n')
    string = string.replace('ŗ', 'r')
    string = string.replace('ş', 's')
    string = string.replace('ţ', 't')
    string = string.replace('Ç', 'C')
    string = string.replace('Ḑ', 'D')
    string = string.replace('Ȩ', 'E')
    string = string.replace('Ģ', 'G')
    string = string.replace('Ḩ', 'H')
    string = string.replace('Ķ', 'K')
    string = string.replace('Ļ', 'L')
    string = string.replace('Ņ', 'N')
    string = string.replace('Ŗ', 'R')
    string = string.replace('Ş', 'S')
    string = string.replace('Ţ', 'T')

    # サーカムフレックス
    string = string.replace('â', 'a')
    string = string.replace('ĉ', 'c')
    string = string.replace('ê', 'e')
    string = string.replace('ĝ', 'g')
    string = string.replace('ĥ', 'h')
    string = string.replace('î', 'i')
    string = string.replace('ĵ', 'j')
    string = string.replace('ô', 'o')
    string = string.replace('ŝ', 's')
    string = string.replace('û', 'u')
    string = string.replace('ŵ', 'w')
    string = string.replace('ŷ', 'y')
    string = string.replace('ẑ', 'z')
    string = string.replace('Â', 'A')
    string = string.replace('Ĉ', 'C')
    string = string.replace('Ê', 'E')
    string = string.replace('Ĝ', 'G')
    string = string.replace('Ĥ', 'H')
    string = string.replace('Î', 'I')
    string = string.replace('Ĵ', 'J')
    string = string.replace('Ô', 'O')
    string = string.replace('Ŝ', 'S')
    string = string.replace('Û', 'U')
    string = string.replace('Ŵ', 'W')
    string = string.replace('Ŷ', 'Y')
    string = string.replace('Ẑ', 'Z')

    # トレマ，ウムラウト
    string = string.replace('ä', 'a')
    string = string.replace('ë', 'e')
    string = string.replace('ḧ', 'h')
    string = string.replace('ï', 'i')
    string = string.replace('ö', 'o')
    string = string.replace('ü', 'u')
    string = string.replace('ẅ', 'w')
    string = string.replace('ẍ', 'x')
    string = string.replace('ÿ', 'y')
    string = string.replace('Ä', 'A')
    string = string.replace('Ë', 'E')
    string = string.replace('Ḧ', 'H')
    string = string.replace('Ï', 'I')
    string = string.replace('Ö', 'O')
    string = string.replace('Ü', 'U')
    string = string.replace('Ẅ', 'W')
    string = string.replace('Ẍ', 'X')
    string = string.replace('Ÿ', 'Y')

    # チルダ
    string = string.replace('ã', 'a')
    string = string.replace('ẽ', 'e')
    string = string.replace('ĩ', 'i')
    string = string.replace('ñ', 'n')
    string = string.replace('õ', 'o')
    string = string.replace('ũ', 'u')
    string = string.replace('ṽ', 'v')
    string = string.replace('ỹ', 'y')
    string = string.replace('Ã', 'A')
    string = string.replace('Ẽ', 'E')
    string = string.replace('Ĩ', 'I')
    string = string.replace('Ñ', 'N')
    string = string.replace('Õ', 'O')
    string = string.replace('Ũ', 'U')
    string = string.replace('Ṽ', 'V')
    string = string.replace('Ỹ', 'Y')

    # 上付きドット符号
    string = string.replace('ȧ', 'a')
    string = string.replace('ḃ', 'b')
    string = string.replace('ċ', 'c')
    string = string.replace('ḋ', 'd')
    string = string.replace('ė', 'e')
    string = string.replace('ḟ', 'f')
    string = string.replace('ġ', 'g')
    string = string.replace('ḣ', 'h')
    string = string.replace('ṁ', 'm')
    string = string.replace('ṅ', 'n')
    string = string.replace('ȯ', 'o')
    string = string.replace('ṗ', 'p')
    string = string.replace('ṙ', 'r')
    string = string.replace('ṡ', 's')
    string = string.replace('ṫ', 't')
    string = string.replace('ẇ', 'w')
    string = string.replace('ẋ', 'x')
    string = string.replace('ẏ', 'y')
    string = string.replace('ż', 'z')
    string = string.replace('Ȧ', 'A')
    string = string.replace('Ḃ', 'B')
    string = string.replace('Ċ', 'C')
    string = string.replace('Ḋ', 'D')
    string = string.replace('Ė', 'E')
    string = string.replace('Ḟ', 'F')
    string = string.replace('Ġ', 'G')
    string = string.replace('Ḣ', 'H')
    string = string.replace('İ', 'I')
    string = string.replace('Ṁ', 'M')
    string = string.replace('Ṅ', 'N')
    string = string.replace('Ȯ', 'O')
    string = string.replace('Ṗ', 'P')
    string = string.replace('Ṙ', 'R')
    string = string.replace('Ṡ', 'S')
    string = string.replace('Ṫ', 'T')
    string = string.replace('Ẇ', 'W')
    string = string.replace('Ẋ', 'X')
    string = string.replace('Ẏ', 'Y')
    string = string.replace('Ż', 'Z')

    # 下付きドット記号
    string = string.replace('ạ', 'a')
    string = string.replace('ḅ', 'b')
    string = string.replace('ḍ', 'd')
    string = string.replace('ẹ', 'e')
    string = string.replace('ḥ', 'h')
    string = string.replace('ị', 'i')
    string = string.replace('ḳ', 'k')
    string = string.replace('ḷ', 'l')
    string = string.replace('ṃ', 'm')
    string = string.replace('ṇ', 'n')
    string = string.replace('ọ', 'o')
    string = string.replace('ṛ', 'r')
    string = string.replace('ṣ', 's')
    string = string.replace('ṭ', 't')
    string = string.replace('ụ', 'u')
    string = string.replace('ṿ', 'v')
    string = string.replace('ẉ', 'w')
    string = string.replace('ỵ', 'y')
    string = string.replace('ẓ', 'z')
    string = string.replace('Ạ', 'A')
    string = string.replace('Ḅ', 'B')
    string = string.replace('Ḍ', 'D')
    string = string.replace('Ẹ', 'E')
    string = string.replace('Ḥ', 'H')
    string = string.replace('Ị', 'I')
    string = string.replace('Ḳ', 'K')
    string = string.replace('Ḷ', 'L')
    string = string.replace('Ṃ', 'M')
    string = string.replace('Ṇ', 'N')
    string = string.replace('Ọ', 'O')
    string = string.replace('Ṛ', 'R')
    string = string.replace('Ṣ', 'S')
    string = string.replace('Ṭ', 'T')
    string = string.replace('Ụ', 'U')
    string = string.replace('Ṿ', 'V')
    string = string.replace('Ẉ', 'W')
    string = string.replace('Ỵ', 'Y')
    string = string.replace('Ẓ', 'Z')

    # 上付きマクロン
    string = string.replace('ā', 'a')
    string = string.replace('ē', 'e')
    string = string.replace('ḡ', 'g')
    string = string.replace('ī', 'i')
    string = string.replace('ō', 'o')
    string = string.replace('ū', 'u')
    string = string.replace('ȳ', 'y')
    string = string.replace('Ā', 'A')
    string = string.replace('Ē', 'E')
    string = string.replace('Ḡ', 'G')
    string = string.replace('Ī', 'I')
    string = string.replace('Ō', 'O')
    string = string.replace('Ū', 'U')
    string = string.replace('Ȳ', 'Y')

    # 下付きマクロン
    string = string.replace('ḇ', 'b')
    string = string.replace('ḏ', 'd')
    string = string.replace('ḵ', 'k')
    string = string.replace('ḻ', 'l')
    string = string.replace('ṉ', 'n')
    string = string.replace('ṟ', 'r')
    string = string.replace('ṯ', 't')
    string = string.replace('ẕ', 'z')
    string = string.replace('Ḇ', 'B')
    string = string.replace('Ḏ', 'D')
    string = string.replace('Ḵ', 'K')
    string = string.replace('Ḻ', 'L')
    string = string.replace('Ṉ', 'N')
    string = string.replace('Ṟ', 'R')
    string = string.replace('Ṯ', 'T')
    string = string.replace('Ẕ', 'Z')

    # リング符号
    string = string.replace('å', 'a')
    string = string.replace('Å', 'A')
    string = string.replace('ů', 'u')
    string = string.replace('Ů', 'U')

    # その他
    string = string.replace('ß', 'B')
    string = string.replace('Æ', 'AE')
    string = string.replace('æ', 'ae')
    string = string.replace('Œ', 'OE')
    string = string.replace('œ', 'oe')
    string = string.replace('Ł', 'L')
    string = string.replace('ł', 'l')
    string = string.replace('Ø', 'O')
    string = string.replace('ø', 'o')
    string = string.replace('Đ', 'D')
    string = string.replace('đ', 'd')
    string = string.replace('Đ', 'D')
    string = string.replace('ð', 'd')
    string = string.replace('Ŋ', 'N')
    string = string.replace('ŋ', 'n')
    string = string.replace('Þ', 'P')
    string = string.replace('þ', 'p')
    string = string.replace('&', 'and')
    
    return string
