# Generated by Django 2.0.13 on 2019-05-04 16:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import paper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='タイトル')),
                ('abstract', models.TextField()),
                ('pdf', models.FileField(upload_to=paper.models.get_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='PDFファイルを添付してださい．')], verbose_name='添付ファイル')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='タグ名')),
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag', to='paper.Tag', verbose_name='タグ'),
        ),
        migrations.AddField(
            model_name='reference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_papers', to=settings.AUTH_USER_MODEL),
        ),
    ]
