# Generated by Django 2.0.13 on 2019-05-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='citation_key',
            field=models.SlugField(default='test', max_length=20, unique=True, verbose_name='引用コード'),
            preserve_default=False,
        ),
    ]
