# Generated by Django 2.0.13 on 2019-05-04 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_auto_20190504_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='abstract',
            field=models.TextField(blank=True, default='', verbose_name='概要'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reference',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_papers', to=settings.AUTH_USER_MODEL, verbose_name='登録ユーザ'),
        ),
    ]
