# Generated by Django 2.0.13 on 2019-05-05 23:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0005_auto_20190504_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paper.Reference')),
                ('author', models.TextField(max_length=100, verbose_name='著者')),
                ('volume', models.CharField(blank=True, max_length=10, verbose_name='vol.')),
                ('number', models.CharField(blank=True, max_length=10, verbose_name='no.')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900, message='1900年より前の年は入力できません．'), django.core.validators.MaxValueValidator(2100, message='2100年より先の年は入力できません．')], verbose_name='出版年')),
                ('page', models.CharField(blank=True, help_text='例: 32-41', max_length=10, validators=[django.core.validators.RegexValidator(message='開始ページ-終了ページ の形式で記入してください (例: 32-41)．', regex='^[0-9]*-[0-9]*$')], verbose_name='ページ数')),
            ],
            bases=('paper.reference',),
        ),
        migrations.CreateModel(
            name='JournalTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='論文誌名')),
                ('publisher', models.CharField(max_length=300, verbose_name='出版元')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_tag', to='paper.JournalTitle', verbose_name='論文誌名'),
        ),
    ]
