# Generated by Django 2.0.13 on 2019-05-06 22:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import paper.models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0006_auto_20190505_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paper.Reference')),
                ('author', models.TextField(help_text='著者を1行に1人ずつ記入してください．', max_length=100, verbose_name='著者')),
                ('page', models.CharField(blank=True, help_text='ページ数を入力してください(例: 32-41)．', max_length=10, validators=[django.core.validators.RegexValidator(message='開始ページ-終了ページ の形式で記入してください (例: 32-41)．', regex='^[0-9]*-[0-9]*$')], verbose_name='ページ数')),
            ],
            bases=('paper.reference',),
        ),
        migrations.CreateModel(
            name='ConferenceTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='会議名')),
                ('year', models.IntegerField(help_text='開催された年を入力してください．', validators=[django.core.validators.MinValueValidator(1900, message='1900年より前の年は入力できません．'), django.core.validators.MaxValueValidator(2100, message='2100年より先の年は入力できません．')], verbose_name='開催年')),
                ('venue', models.CharField(blank=True, help_text='開催地を入力してください(例1: Kyoto, Japan，例2: Miami, FL, USA，例3: Shanghai, China)', max_length=100, verbose_name='開催地')),
            ],
        ),
        migrations.AlterField(
            model_name='journal',
            name='author',
            field=models.TextField(help_text='著者を1行に1人ずつ記入してください．', max_length=100, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_title',
            field=models.ForeignKey(help_text='論文誌名を入力してください．一覧になければ，新しく登録してください．', on_delete=django.db.models.deletion.CASCADE, related_name='journal_title', to='paper.JournalTitle', verbose_name='論文誌名'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='page',
            field=models.CharField(blank=True, help_text='ページ数を入力してください(例: 32-41)．', max_length=10, validators=[django.core.validators.RegexValidator(message='開始ページ-終了ページ の形式で記入してください (例: 32-41)．', regex='^[0-9]*-[0-9]*$')], verbose_name='ページ数'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='year',
            field=models.IntegerField(help_text='出版された年を入力してください．', validators=[django.core.validators.MinValueValidator(1900, message='1900年より前の年は入力できません．'), django.core.validators.MaxValueValidator(2100, message='2100年より先の年は入力できません．')], verbose_name='出版年'),
        ),
        migrations.AlterField(
            model_name='journaltitle',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='論文誌名'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='abstract',
            field=models.TextField(blank=True, help_text='内容に関するメモを記入してください．', verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='citation_key',
            field=models.SlugField(default=None, help_text='第一著者名と出版年から自動で生成されます．', max_length=20, null=True, unique=True, verbose_name='引用コード'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='pdf',
            field=models.FileField(help_text='原稿のファイルを登録してください．', upload_to=paper.models.get_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='PDFファイルを添付してださい．')], verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='関連するタグを付与してください．一覧になければ，新しく登録してください．', related_name='tag', to='paper.Tag', verbose_name='タグ'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.CharField(help_text='論文のタイトルを入力してください．', max_length=300, unique=True, verbose_name='タイトル'),
        ),
        migrations.AddField(
            model_name='conference',
            name='conference_title',
            field=models.ForeignKey(help_text='会議名を入力してください．一覧になければ，新しく登録してください．', on_delete=django.db.models.deletion.CASCADE, related_name='conference_title', to='paper.ConferenceTitle', verbose_name='会議名'),
        ),
    ]
