# Generated by Django 2.0.13 on 2019-05-06 22:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paper', '0007_auto_20190506_2243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conference',
            new_name='ConferencePaper',
        ),
        migrations.RenameModel(
            old_name='Journal',
            new_name='JournalPaper',
        ),
    ]
