# Generated by Django 2.0.13 on 2019-05-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0008_auto_20190506_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencetitle',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=None, help_text='開催された月を入力してください．', null=True, verbose_name='開催月'),
        ),
        migrations.AddField(
            model_name='journalpaper',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=None, help_text='出版された月を入力してください．', null=True, verbose_name='出版月'),
        ),
    ]
