# Generated by Django 2.0.13 on 2019-05-07 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0010_auto_20190507_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='report',
        ),
    ]
