# Generated by Django 2.0.13 on 2019-05-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0011_remove_reference_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencetitle',
            name='organizer',
            field=models.CharField(blank=True, help_text='会議の主催者を入力してください(例: IEEE，ACM，IFIP，IEICE)．', max_length=100, null=True, verbose_name='主催者'),
        ),
    ]
