# Generated by Django 2.0.13 on 2019-05-09 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paper', '0012_conferencetitle_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurConferencePaper',
            fields=[
                ('conferencepaper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paper.ConferencePaper')),
                ('presenter', models.CharField(help_text='発表者を入力してください．', max_length=20, verbose_name='発表者')),
                ('short_paper', models.BooleanField(default=False, help_text='ショートペーパーの場合，チェックを入れてください．', verbose_name='ショートペーパー')),
                ('poster', models.BooleanField(default=False, help_text='ポスター発表の場合，チェックを入れてください．', verbose_name='ポスター発表')),
                ('invited', models.BooleanField(default=False, help_text='招待発表の場合，チェックを入れてください．', verbose_name='招待発表')),
                ('user', models.ManyToManyField(default=None, help_text='研究室メンバのうち著者に含まれるメンバを登録してください．', related_name='conference_users', to=settings.AUTH_USER_MODEL, verbose_name='研究室内著者')),
            ],
            bases=('paper.conferencepaper',),
        ),
        migrations.CreateModel(
            name='OurJournalPaper',
            fields=[
                ('journalpaper_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paper.JournalPaper')),
                ('letter', models.BooleanField(default=False, help_text='レターの場合，チェックを入れてください．', verbose_name='レター')),
                ('invited', models.BooleanField(default=False, help_text='招待論文の場合，チェックを入れてください．', verbose_name='招待論文')),
                ('user', models.ManyToManyField(default=None, help_text='研究室メンバのうち著者に含まれるメンバを登録してください．', related_name='journal_users', to=settings.AUTH_USER_MODEL, verbose_name='研究室内著者')),
            ],
            bases=('paper.journalpaper',),
        ),
        migrations.AlterField(
            model_name='conferencepaper',
            name='conference_title',
            field=models.ForeignKey(help_text='会議名を入力してください．一覧になければ，新しく登録してください．必要に応じて Poster，Poster Track，Mini-conferenceなどを付記してください．', on_delete=django.db.models.deletion.CASCADE, related_name='conference_title', to='paper.ConferenceTitle', verbose_name='会議名'),
        ),
    ]
