# Generated by Django 2.0.13 on 2019-05-09 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0013_auto_20190509_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourconferencepaper',
            old_name='user',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='ourjournalpaper',
            old_name='user',
            new_name='author_user',
        ),
    ]
