# Generated by Django 2.0.13 on 2019-05-09 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0014_auto_20190509_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourconferencepaper',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='発表年月日'),
        ),
        migrations.AddField(
            model_name='ourjournalpaper',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='出版年月日'),
        ),
    ]
