# Generated by Django 2.0.13 on 2019-05-10 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0015_auto_20190509_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalpaper',
            name='year',
            field=models.IntegerField(help_text='出版された年を入力してください．', null=True, validators=[django.core.validators.MinValueValidator(1900, message='1900年より前の年は入力できません．'), django.core.validators.MaxValueValidator(2100, message='2100年より先の年は入力できません．')], verbose_name='出版年'),
        ),
    ]
