# Generated by Django 2.0.13 on 2019-05-10 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0016_auto_20190510_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourjournalpaper',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='出版年月日'),
        ),
    ]
