# Generated by Django 2.0.13 on 2019-05-10 18:40

import django.core.validators
from django.db import migrations, models
import paper.models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0018_auto_20190510_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencepaper',
            name='presentation_id',
            field=models.CharField(blank=True, help_text='研究会，および総合大会，ソサイエティ大会の場合は発表IDを入力してください(例1: NS2017-198，例2: IN2018-131，例3: B-7-23，例4: 3D-1)．', max_length=20, null=True, verbose_name='発表ID'),
        ),
        migrations.AddField(
            model_name='conferencetitle',
            name='country',
            field=models.CharField(blank=True, help_text='開催国(米国，カナダの場合は州の略号)を入力してください(例1: Japan，例2: FL, USA，例3: China)．', max_length=100, verbose_name='開催国'),
        ),
        migrations.AlterField(
            model_name='conferencepaper',
            name='author',
            field=models.TextField(help_text='著者を1行に1人ずつ，姓と名の間に半角スペースを入れて記入してください．', max_length=100, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='conferencetitle',
            name='organizer',
            field=models.CharField(blank=True, help_text='会議の主催者を入力してください(例: IEEE，ACM，IFIP，IEICE，電子情報通信学会)．', max_length=100, null=True, verbose_name='主催者'),
        ),
        migrations.AlterField(
            model_name='conferencetitle',
            name='venue',
            field=models.CharField(blank=True, help_text='開催都市を入力してください(例1: Kyoto，例2: Miami，例3: Shanghai，例4: 神奈川)．', max_length=100, verbose_name='開催都市'),
        ),
        migrations.AlterField(
            model_name='journalpaper',
            name='author',
            field=models.TextField(help_text='著者を1行に1人ずつ，姓と名の間に半角スペースを入れて記入してください．', max_length=100, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='ourconferencepaper',
            name='invited',
            field=models.BooleanField(default=False, help_text='招待講演の場合，チェックを入れてください．', verbose_name='招待講演'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='pdf',
            field=models.FileField(blank=True, help_text='原稿のファイルを登録してください．', upload_to=paper.models.get_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='PDFファイルを添付してださい．')], verbose_name='添付ファイル'),
        ),
    ]
