# Generated by Django 2.0.13 on 2019-05-13 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0020_auto_20190512_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencepaper',
            name='page',
            field=models.CharField(blank=True, help_text='ページ数を入力してください(例1: 32-41，例2: 56)．', max_length=10, validators=[django.core.validators.RegexValidator(message='開始ページ-終了ページ の形式で記入してください (例: 32-41)．1ページの原稿の場合はハイフンは不要です(例: 56)．', regex='^[0-9]*-[0-9]*$|^[0-9]*$')], verbose_name='ページ数'),
        ),
    ]
