# Generated by Django 2.0.13 on 2019-06-09 20:30

from django.db import migrations, models
import paper.models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0022_auto_20190513_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourconferencepaper',
            name='keynote',
            field=models.BooleanField(default=False, help_text='基調講演の場合，チェックを入れてください．', verbose_name='基調講演'),
        ),
        migrations.AlterField(
            model_name='conferencepaper',
            name='author',
            field=models.TextField(help_text='著者を1行に1人ずつ，姓と名の間に半角スペースを入れて記入してください．必要に応じて以下の拡張文字を使用してください<br>áćéǵíḱĺḿńóṕŕśúẃýź ÁĆÉǴÍḰĹḾŃÓṔŔŚÚẂÝŹ őűŐŰ àèìǹòùẁỳÀÈÌǸÒÙẀỲ ăĕğĭŏŭĂĔĞĬŎŬ ǎčěǧȟǩňǒřšǔžǍČĎĚǦȞǨǏŇǑŘŠŤǓŽ<br>çḑȩḩķļņŗşţÇḐȨĢḨĶĻŅŖŞŢ âĉêĝĥîĵôŝûŵŷẑÂĈÊĜĤÎĴÔŜÛŴŶẐ äëḧïöüẅẍÿÄËḦÏÖÜẄẌŸ ãẽĩñõũṽỹÃẼĨÑÕŨṼỸ<br>ȧḃċḋėḟġḣṁṅȯṗṙṡṫẇẋẏżȦḂĊḊĖḞĠḢİṀṄȮṖṘṠṪẆẊẎŻ ạḅḍẹḥịḳḷṃṇọṛṣṭụṿẉỵẓẠḄḌẸḤỊḲḶṂṆỌṚṢṬỤṾẈỴẒ<br>āēḡīōūȳĀĒḠĪŌŪȲ ḇḏḵḻṉṟṯẕḆḎḴḺṈṞṮẔ åÅůŮ ßÆæŒœŁłØøĐđĐðŊŋÞþ', max_length=100, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='conferencetitle',
            name='name',
            field=models.CharField(help_text='会議名を記入してください．研究会では下記の例のように，信学技報のvolとnoを付記してください．会議名は正式名称で，国際会議は()で略称を記入してください．Workshop, Poster, Mini-conferenceなどは本会議とは分けて登録してください．<br>The 31st IEEE International Conference on Computer Communication (INFOCOM 2012)<br>The 15th Annual International Conference on Mobile Computing and Networking (MobiCom 2009) Workshop<br>2003 IEEE International Conference on Communications (ICC 2003)<br>電子情報通信学会 情報ネットワーク研究会, 信学技報, vol. 109, no. 119<br>2015年 電子情報通信学会 信越支部大会<br>', max_length=200, unique=True, validators=[paper.models.kenkyukai_validator], verbose_name='会議名'),
        ),
        migrations.AlterField(
            model_name='journalpaper',
            name='author',
            field=models.TextField(help_text='著者を1行に1人ずつ，姓と名の間に半角スペースを入れて記入してください．必要に応じて以下の拡張文字を使用してください<br>áćéǵíḱĺḿńóṕŕśúẃýź ÁĆÉǴÍḰĹḾŃÓṔŔŚÚẂÝŹ őűŐŰ àèìǹòùẁỳÀÈÌǸÒÙẀỲ ăĕğĭŏŭĂĔĞĬŎŬ ǎčěǧȟǩňǒřšǔžǍČĎĚǦȞǨǏŇǑŘŠŤǓŽ<br>çḑȩḩķļņŗşţÇḐȨĢḨĶĻŅŖŞŢ âĉêĝĥîĵôŝûŵŷẑÂĈÊĜĤÎĴÔŜÛŴŶẐ äëḧïöüẅẍÿÄËḦÏÖÜẄẌŸ ãẽĩñõũṽỹÃẼĨÑÕŨṼỸ<br>ȧḃċḋėḟġḣṁṅȯṗṙṡṫẇẋẏżȦḂĊḊĖḞĠḢİṀṄȮṖṘṠṪẆẊẎŻ ạḅḍẹḥịḳḷṃṇọṛṣṭụṿẉỵẓẠḄḌẸḤỊḲḶṂṆỌṚṢṬỤṾẈỴẒ<br>āēḡīōūȳĀĒḠĪŌŪȲ ḇḏḵḻṉṟṯẕḆḎḴḺṈṞṮẔ åÅůŮ ßÆæŒœŁłØøĐđĐðŊŋÞþ', max_length=100, verbose_name='著者'),
        ),
    ]
