# Generated by Django 2.0.13 on 2019-06-16 16:35

from django.db import migrations, models
import paper.models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0023_auto_20190609_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencetitle',
            name='snip',
            field=models.TextField(blank=True, help_text='研究室メンバが著者にいる論文でSNIPが記録されている会議の場合は，1行に1年分ずつ，SNIPを記入してください．例) 2018:1.737', max_length=100, null=True, validators=[paper.models.yearly_score_validator], verbose_name='SNIP'),
        ),
        migrations.AddField(
            model_name='journaltitle',
            name='impact_factor',
            field=models.TextField(blank=True, help_text='研究室メンバが著者にいる論文の場合は，1行に1年分ずつ，インパクトファクターを記入してください．例) 2018:1.737', max_length=100, null=True, validators=[paper.models.yearly_score_validator], verbose_name='IF'),
        ),
        migrations.AddField(
            model_name='journaltitle',
            name='snip',
            field=models.TextField(blank=True, help_text='研究室メンバが著者にいる論文の場合は，1行に1年分ずつ，SNIPを記入してください．例) 2018:1.737', max_length=100, null=True, validators=[paper.models.yearly_score_validator], verbose_name='SNIP'),
        ),
        migrations.AlterField(
            model_name='ourjournalpaper',
            name='published_date',
            field=models.DateField(default=None, help_text='出版年月日を入力してください．オンライン版が先に公開されている場合は，そちらの公開日を入力してください．', verbose_name='出版年月日'),
        ),
    ]
