# Generated by Django 2.0.13 on 2019-06-17 15:10

import django.core.validators
from django.db import migrations, models
import paper.models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0025_auto_20190616_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencepaper',
            name='author',
            field=models.TextField(help_text='著者を1行に1人ずつ，姓と名の間に半角スペースを入れて記入してください．必要に応じて以下の拡張文字を使用してください<br>áćéǵíḱĺḿńóṕŕśúẃýź ÁĆÉǴÍḰĹḾŃÓṔŔŚÚẂÝŹ őűŐŰ àèìǹòùẁỳÀÈÌǸÒÙẀỲ ăĕğĭŏŭĂĔĞĬŎŬ ǎčěǧȟǩňǒřšǔžǍČĎĚǦȞǨǏŇǑŘŠŤǓŽ<br>çḑȩḩķļņŗşţÇḐȨĢḨĶĻŅŖŞŢ âĉêĝĥîĵôŝûŵŷẑÂĈÊĜĤÎĴÔŜÛŴŶẐ äëḧïöüẅẍÿÄËḦÏÖÜẄẌŸ ãẽĩñõũṽỹÃẼĨÑÕŨṼỸ<br>ȧḃċḋėḟġḣṁṅȯṗṙṡṫẇẋẏżȦḂĊḊĖḞĠḢİṀṄȮṖṘṠṪẆẊẎŻ ạḅḍẹḥịḳḷṃṇọṛṣṭụṿẉỵẓẠḄḌẸḤỊḲḶṂṆỌṚṢṬỤṾẈỴẒ<br>āēḡīōūȳĀĒḠĪŌŪȲ ḇḏḵḻṉṟṯẕḆḎḴḺṈṞṮẔ åÅůŮ ßÆæŒœŁłØøĐđĐðŊŋÞþ', max_length=300, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='conferencepaper',
            name='page',
            field=models.CharField(blank=True, help_text='ページ数を入力してください(例1: 32-41，例2: 56)．', max_length=20, validators=[django.core.validators.RegexValidator(message='開始ページ-終了ページ の形式で記入してください (例: 32-41)．1ページの原稿の場合はハイフンは不要です(例: 56)．', regex='^[0-9]+-[0-9]+$|^[0-9]*$')], verbose_name='ページ数'),
        ),
        migrations.AlterField(
            model_name='conferencetitle',
            name='name',
            field=models.CharField(help_text='会議名を記入してください．研究会では下記の例のように，信学技報のvolとnoを付記してください．会議名は正式名称で，国際会議は()で略称を記入してください．Workshop, Poster, Mini-conferenceなどは本会議とは分けて登録してください．<br>The 31st IEEE International Conference on Computer Communication (INFOCOM 2012)<br>The 15th Annual International Conference on Mobile Computing and Networking (MobiCom 2009) Workshop<br>2003 IEEE International Conference on Communications (ICC 2003)<br>電子情報通信学会 情報ネットワーク研究会, 信学技報, vol. 109, no. 119<br>2015年 電子情報通信学会 信越支部大会<br>', max_length=400, unique=True, validators=[paper.models.kenkyukai_validator], verbose_name='会議名'),
        ),
        migrations.AlterField(
            model_name='conferencetitle',
            name='organizer',
            field=models.CharField(blank=True, help_text='会議の主催者を入力してください(例: IEEE，ACM，IFIP，IEICE，電子情報通信学会)．', max_length=400, null=True, verbose_name='主催者'),
        ),
        migrations.AlterField(
            model_name='conferencetitle',
            name='snip',
            field=models.FloatField(blank=True, help_text='研究室メンバが著者にいる論文でSNIPが記録されている会議の場合は，この年の会議のSNIPを記入してください．', max_length=400, null=True, verbose_name='SNIP'),
        ),
        migrations.AlterField(
            model_name='journalpaper',
            name='author',
            field=models.TextField(help_text='著者を1行に1人ずつ，姓と名の間に半角スペースを入れて記入してください．必要に応じて以下の拡張文字を使用してください<br>áćéǵíḱĺḿńóṕŕśúẃýź ÁĆÉǴÍḰĹḾŃÓṔŔŚÚẂÝŹ őűŐŰ àèìǹòùẁỳÀÈÌǸÒÙẀỲ ăĕğĭŏŭĂĔĞĬŎŬ ǎčěǧȟǩňǒřšǔžǍČĎĚǦȞǨǏŇǑŘŠŤǓŽ<br>çḑȩḩķļņŗşţÇḐȨĢḨĶĻŅŖŞŢ âĉêĝĥîĵôŝûŵŷẑÂĈÊĜĤÎĴÔŜÛŴŶẐ äëḧïöüẅẍÿÄËḦÏÖÜẄẌŸ ãẽĩñõũṽỹÃẼĨÑÕŨṼỸ<br>ȧḃċḋėḟġḣṁṅȯṗṙṡṫẇẋẏżȦḂĊḊĖḞĠḢİṀṄȮṖṘṠṪẆẊẎŻ ạḅḍẹḥịḳḷṃṇọṛṣṭụṿẉỵẓẠḄḌẸḤỊḲḶṂṆỌṚṢṬỤṾẈỴẒ<br>āēḡīōūȳĀĒḠĪŌŪȲ ḇḏḵḻṉṟṯẕḆḎḴḺṈṞṮẔ åÅůŮ ßÆæŒœŁłØøĐđĐðŊŋÞþ', max_length=300, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='journalpaper',
            name='page',
            field=models.CharField(blank=True, help_text='ページ数を入力してください(例: 32-41)．', max_length=20, validators=[django.core.validators.RegexValidator(message='開始ページ-終了ページ の形式で記入してください (例: 32-41)．', regex='^[0-9]+-[0-9]+$|^[0-9]*$')], verbose_name='ページ数'),
        ),
        migrations.AlterField(
            model_name='journaltitle',
            name='impact_factor',
            field=models.TextField(blank=True, help_text='研究室メンバが著者にいる論文の場合は，1行に1年分ずつ，インパクトファクターを記入してください．例) 2018:1.737', max_length=400, null=True, validators=[paper.models.yearly_score_validator], verbose_name='IF'),
        ),
        migrations.AlterField(
            model_name='journaltitle',
            name='name',
            field=models.CharField(max_length=400, unique=True, verbose_name='論文誌名'),
        ),
        migrations.AlterField(
            model_name='journaltitle',
            name='snip',
            field=models.TextField(blank=True, help_text='研究室メンバが著者にいる論文の場合は，1行に1年分ずつ，SNIPを記入してください．例) 2018:1.737', max_length=400, null=True, validators=[paper.models.yearly_score_validator], verbose_name='SNIP'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='citation_key',
            field=models.SlugField(default=None, help_text='第一著者名と出版年から自動で生成されます．', max_length=30, null=True, unique=True, verbose_name='引用コード'),
        ),
    ]
