# Generated by Django 2.0.13 on 2019-06-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0026_auto_20190617_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='citation_key',
            field=models.CharField(default=None, help_text='第一著者名と出版年から自動で生成されます．', max_length=30, null=True, unique=True, verbose_name='引用コード'),
        ),
    ]
