# Generated by Django 2.0.13 on 2019-07-10 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0027_auto_20190618_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlReference',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paper.Reference')),
                ('url', models.URLField(help_text='引用するサイトのURLを入力してください．', max_length=400, verbose_name='URL')),
            ],
            bases=('paper.reference',),
        ),
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.CharField(help_text='文献のタイトルを入力してください．', max_length=300, validators=[django.core.validators.RegexValidator(inverse_match=True, message='すべて大文字で入力することはできません．', regex="^[A-Z\\s:;\\-~?']*$")], verbose_name='タイトル'),
        ),
    ]
