# Generated by Django 2.0.13 on 2019-08-04 18:42

import django.core.validators
from django.db import migrations, models
import paper.models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0029_auto_20190804_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourconferencepaper',
            name='post_print',
            field=models.FileField(blank=True, help_text='国際会議の場合は，Post-print(出版版ではなく査読後の投稿時原稿)のファイルを登録してください．', upload_to=paper.models.get_upload_to_post_print, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='PDFファイルを添付してださい．')], verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='ourconferencepaper',
            name='pre_print',
            field=models.FileField(blank=True, help_text='国際会議の場合は，Pre-print(査読前の投稿時原稿)のファイルを登録してください．', upload_to=paper.models.get_upload_to_pre_print, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='PDFファイルを添付してださい．')], verbose_name='添付ファイル'),
        ),
    ]
