# Generated by Django 2.0.13 on 2019-08-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0030_auto_20190804_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourconferencepaper',
            name='doi',
            field=models.CharField(blank=True, help_text='DOIを入力してください．(例: 10.1109/TIT.2016.2636847)', max_length=20, null=True, verbose_name='DOI'),
        ),
        migrations.AddField(
            model_name='ourjournalpaper',
            name='doi',
            field=models.CharField(blank=True, help_text='DOIを入力してください．(例: 10.1109/TIT.2016.2636847)', max_length=20, null=True, verbose_name='DOI'),
        ),
    ]
