# Generated by Django 2.0.13 on 2019-08-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0031_auto_20190814_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourconferencepaper',
            name='url',
            field=models.URLField(blank=True, help_text='IEEE eXplore，ACM Digital Library，ScienceDirect など，公式のPDFが公開されているページのURLを入力してください．(例: https://ieeexplore.ieee.org/document/8526826，例: https://dl.acm.org/citation.cfm?id=2833277，)', max_length=400, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='ourjournalpaper',
            name='url',
            field=models.URLField(blank=True, help_text='IEEE eXplore，ACM Digital Library，ScienceDirect など，公式のPDFが公開されているページのURLを入力してください．(例: https://ieeexplore.ieee.org/document/8526826，例: https://dl.acm.org/citation.cfm?id=2833277，)', max_length=400, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='ourconferencepaper',
            name='doi',
            field=models.CharField(blank=True, help_text='論文誌及び国際会議の場合は，DOIを入力してください．(例: 10.1109/TIT.2016.2636847)', max_length=20, null=True, verbose_name='DOI'),
        ),
    ]
