# Generated by Django 2.0.13 on 2019-08-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0032_auto_20190815_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourjournalpaper',
            name='doi',
            field=models.CharField(blank=True, help_text='DOIを入力してください．(例: 10.1109/TIT.2016.2636847)', max_length=30, null=True, verbose_name='DOI'),
        ),
    ]
