# Generated by Django 2.0.13 on 2019-08-17 18:07

from django.db import migrations, models
import paper.models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0034_auto_20190816_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltitle',
            name='fwci',
            field=models.TextField(blank=True, help_text='研究室メンバが著者にいる論文の場合は，{"年":値, "年":値, ...} のJSON形式でFWCIを記入してください．例) {"2018":1.737, "2019":2.000}', max_length=400, null=True, validators=[paper.models.score_json_validator], verbose_name='FWCI'),
        ),
        migrations.AlterField(
            model_name='journaltitle',
            name='impact_factor',
            field=models.TextField(blank=True, help_text='研究室メンバが著者にいる論文の場合は，{"年":値, "年":値, ...} のJSON形式でインパクトファクターを記入してください．例) {"2018":1.737, "2019":2.000}', max_length=400, null=True, validators=[paper.models.score_json_validator], verbose_name='IF'),
        ),
        migrations.AlterField(
            model_name='journaltitle',
            name='snip',
            field=models.TextField(blank=True, help_text='研究室メンバが著者にいる論文の場合は，{"年":値, "年":値, ...} のJSON形式でSNIPを記入してください．例) {"2018":1.737, "2019":2.000}', max_length=400, null=True, validators=[paper.models.score_json_validator], verbose_name='SNIP'),
        ),
    ]
