# Generated by Django 2.0.13 on 2019-08-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0037_auto_20190819_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourconferencepaper',
            name='scopus_cite',
            field=models.IntegerField(blank=True, default=None, help_text='Scopusの引用数を表示します．', max_length=400, null=True, verbose_name='Scopus引用数'),
        ),
        migrations.AlterField(
            model_name='ourjournalpaper',
            name='scopus_cite',
            field=models.IntegerField(blank=True, default=None, help_text='Scopusの引用数を表示します．', max_length=400, null=True, verbose_name='Scopus引用数'),
        ),
    ]
