# Generated by Django 2.0.13 on 2019-08-20 22:33

from django.db import migrations, models
import paper.models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0039_auto_20190819_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journaltitle',
            name='fwci',
        ),
        migrations.AlterField(
            model_name='conferencetitle',
            name='snip',
            field=models.FloatField(blank=True, help_text='研究室メンバが著者にいる論文でSNIPが記録されている会議の場合は，この年の会議のSNIPが記録されます．', max_length=400, null=True, verbose_name='SNIP'),
        ),
        migrations.AlterField(
            model_name='journaltitle',
            name='impact_factor',
            field=models.TextField(blank=True, help_text='研究室メンバが著者にいる論文の場合は，{"年":値, "年":値, ...} のJSON形式でインパクトファクターが記録されます．例) {"2018":1.737, "2019":2.000}', max_length=400, null=True, validators=[paper.models.score_json_validator], verbose_name='IF'),
        ),
        migrations.AlterField(
            model_name='journaltitle',
            name='snip',
            field=models.TextField(blank=True, help_text='研究室メンバが著者にいる論文の場合は，{"年":値, "年":値, ...} のJSON形式でSNIPが記録されます．例) {"2018":1.737, "2019":2.000}', max_length=400, null=True, validators=[paper.models.score_json_validator], verbose_name='SNIP'),
        ),
    ]
