# Generated by Django 2.0.13 on 2019-08-23 17:22

import django.core.validators
from django.db import migrations, models
import paper.models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0041_auto_20190820_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourconferencepaper',
            name='core_rank',
            field=models.CharField(blank=True, default=None, help_text='CORE Ranking (http://portal.core.edu.au/conf-ranks/) に掲載されている国際会議の場合は，CORE Rankを記入してください．(例: A*，C)', max_length=3, null=True, verbose_name='CORE Rank'),
        ),
        migrations.AlterField(
            model_name='conferencepaper',
            name='author',
            field=models.TextField(help_text='著者を1行に1人ずつ，姓と名の間に半角スペースを入れて記入してください．必要に応じて以下の拡張文字を使用してください\náćéǵíḱĺḿńóṕŕśúẃýź ÁĆÉǴÍḰĹḾŃÓṔŔŚÚẂÝŹ őűŐŰ àèìǹòùẁỳÀÈÌǸÒÙẀỲ ăĕğĭŏŭĂĔĞĬŎŬ ǎčěǧȟǩňǒřšǔžǍČĎĚǦȞǨǏŇǑŘŠŤǓŽ\nçḑȩḩķļņŗşţÇḐȨĢḨĶĻŅŖŞŢ âĉêĝĥîĵôŝûŵŷẑÂĈÊĜĤÎĴÔŜÛŴŶẐ äëḧïöüẅẍÿÄËḦÏÖÜẄẌŸ ãẽĩñõũṽỹÃẼĨÑÕŨṼỸ\nȧḃċḋėḟġḣṁṅȯṗṙṡṫẇẋẏżȦḂĊḊĖḞĠḢİṀṄȮṖṘṠṪẆẊẎŻ ạḅḍẹḥịḳḷṃṇọṛṣṭụṿẉỵẓẠḄḌẸḤỊḲḶṂṆỌṚṢṬỤṾẈỴẒ\nāēḡīōūȳĀĒḠĪŌŪȲ ḇḏḵḻṉṟṯẕḆḎḴḺṈṞṮẔ åÅůŮ ßÆæŒœŁłØøĐđĐðŊŋÞþ', max_length=300, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='conferencetitle',
            name='name',
            field=models.CharField(help_text='会議名を記入してください．研究会では下記の例のように，信学技報のvolとnoを付記してください．会議名は正式名称で，国際会議は()で略称を記入してください．Workshop, Poster, Mini-conferenceなどは本会議とは分けて登録してください．\nThe 31st IEEE International Conference on Computer Communication (INFOCOM 2012)\nThe 15th Annual International Conference on Mobile Computing and Networking (MobiCom 2009) Workshop\n2003 IEEE International Conference on Communications (ICC 2003)\n電子情報通信学会 情報ネットワーク研究会, 信学技報, vol. 109, no. 119\n2015年 電子情報通信学会 信越支部大会\n', max_length=400, unique=True, validators=[paper.models.kenkyukai_validator], verbose_name='会議名'),
        ),
        migrations.AlterField(
            model_name='journalpaper',
            name='author',
            field=models.TextField(help_text='著者を1行に1人ずつ，姓と名の間に半角スペースを入れて記入してください．必要に応じて以下の拡張文字を使用してください\náćéǵíḱĺḿńóṕŕśúẃýź ÁĆÉǴÍḰĹḾŃÓṔŔŚÚẂÝŹ őűŐŰ àèìǹòùẁỳÀÈÌǸÒÙẀỲ ăĕğĭŏŭĂĔĞĬŎŬ ǎčěǧȟǩňǒřšǔžǍČĎĚǦȞǨǏŇǑŘŠŤǓŽ\nçḑȩḩķļņŗşţÇḐȨĢḨĶĻŅŖŞŢ âĉêĝĥîĵôŝûŵŷẑÂĈÊĜĤÎĴÔŜÛŴŶẐ äëḧïöüẅẍÿÄËḦÏÖÜẄẌŸ ãẽĩñõũṽỹÃẼĨÑÕŨṼỸ\nȧḃċḋėḟġḣṁṅȯṗṙṡṫẇẋẏżȦḂĊḊĖḞĠḢİṀṄȮṖṘṠṪẆẊẎŻ ạḅḍẹḥịḳḷṃṇọṛṣṭụṿẉỵẓẠḄḌẸḤỊḲḶṂṆỌṚṢṬỤṾẈỴẒ\nāēḡīōūȳĀĒḠĪŌŪȲ ḇḏḵḻṉṟṯẕḆḎḴḺṈṞṮẔ åÅůŮ ßÆæŒœŁłØøĐđĐðŊŋÞþ', max_length=300, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.CharField(help_text='文献のタイトルを入力してください．\n数式や数学記号を含む場合は，$\\lambda$のように$マークで挟んだLaTeX形式で入力してください．．', max_length=300, validators=[django.core.validators.RegexValidator(inverse_match=True, message='すべて大文字で入力することはできません．', regex="^[A-Z\\s:;\\-~?']*$")], verbose_name='タイトル'),
        ),
    ]
