# Generated by Django 2.0.13 on 2019-08-25 16:08

from django.db import migrations, models
import paper.models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0042_auto_20190823_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencetitle',
            name='cite_score',
            field=models.FloatField(blank=True, help_text='研究室メンバが著者にいる論文でCiteScoreが記録されている会議の場合は，この年の会議のCiteScoreが記録されます．', max_length=400, null=True, verbose_name='CiteScore'),
        ),
        migrations.AddField(
            model_name='conferencetitle',
            name='highest_percentile',
            field=models.CharField(blank=True, help_text='研究室メンバが著者にいる論文でHighest percentileが記録されている会議の場合は，この年の会議のHighest percentileが記録されます．', max_length=200, null=True, verbose_name='Highest percentile'),
        ),
        migrations.AddField(
            model_name='journaltitle',
            name='cite_score',
            field=models.TextField(blank=True, help_text='研究室メンバが著者にいる論文の場合は，{"年":値, "年":値, ...} のJSON形式でCiteScoreが記録されます．例) {"2018":1.737, "2019":2.000}', max_length=400, null=True, validators=[paper.models.score_json_validator], verbose_name='CiteScore'),
        ),
        migrations.AddField(
            model_name='journaltitle',
            name='highest_percentile',
            field=models.TextField(blank=True, help_text='研究室メンバが著者にいる論文の場合は，{"年":"パーセンタイル, 順位/母数, 分野", "年":"パーセンタイル, 順位/母数, 分野", ...} のJSON形式でScopusのHighest percentileが記録されます．例) {"2018":"90.0%, 19/204, General Computer Science", ...}', max_length=400, null=True, validators=[paper.models.score_json_validator], verbose_name='Highest percentile'),
        ),
        migrations.AlterField(
            model_name='ourconferencepaper',
            name='core_rank',
            field=models.CharField(blank=True, default=None, help_text='に掲載されている国際会議の場合は，CORE Rankを記入してください．(例: A*，C)', max_length=3, null=True, verbose_name='CORE Rank'),
        ),
    ]
