# Generated by Django 2.0.13 on 2019-10-09 11:22

import django.core.validators
from django.db import migrations, models
import paper.models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0043_auto_20190825_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourconferencepaper',
            name='presentation_pdf',
            field=models.FileField(blank=True, help_text='プレゼンテーションまたはポスターのPDFファイルを登録してください．', upload_to=paper.models.get_upload_to_presentation_pdf, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='PDFファイルを添付してださい．')], verbose_name='添付ファイル'),
        ),
    ]
