# Generated by Django 2.0.13 on 2019-10-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_auto_20191007_2329'),
        ('paper', '0044_ourconferencepaper_presentation_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourconferencepaper',
            name='subject',
            field=models.ManyToManyField(default=None, help_text='関連する研究テーマを登録してください．', related_name='conference_subject', to='public.Research', verbose_name='関連テーマ'),
        ),
        migrations.AlterField(
            model_name='ourconferencepaper',
            name='doi',
            field=models.CharField(blank=True, help_text='論文誌及び国際会議の場合は，DOIを入力してください．(例: 10.1109/TIT.2016.2636847)', max_length=30, null=True, verbose_name='DOI'),
        ),
    ]
