# Generated by Django 2.0.13 on 2020-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0045_auto_20191012_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourconferencepaper',
            name='subject',
            field=models.ManyToManyField(blank=True, default=None, help_text='関連する研究テーマを登録してください．', null=True, related_name='conference_subject', to='public.Research', verbose_name='関連テーマ'),
        ),
    ]
