# Generated by Django 2.0.13 on 2020-04-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0046_auto_20200402_1348'),
        ('paper', '0046_auto_20200407_1322'),
    ]

    operations = [
    ]
