# Generated by Django 2.0.13 on 2020-04-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0047_merge_20200408_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencetitle',
            name='country',
            field=models.CharField(blank=True, help_text='開催国(米国，カナダ等の場合は州の略号と開催国)を入力してください(例1: Japan，例2: 日本, 例3: FL, USA，例4: China)．', max_length=100, verbose_name='開催国'),
        ),
        migrations.AlterField(
            model_name='journaltitle',
            name='name',
            field=models.CharField(help_text='論文誌の名前を入力してください．(例: IEICE Transactions on Communications)', max_length=400, unique=True, verbose_name='論文誌名'),
        ),
        migrations.AlterField(
            model_name='journaltitle',
            name='publisher',
            field=models.CharField(help_text='学会や出版社など，出版元を入力してください．(例: IEICE，IEEE，Elsevier)', max_length=300, verbose_name='出版元'),
        ),
    ]
