# Generated by Django 2.0.13 on 2020-04-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0048_auto_20200408_1740'),
        ('paper', '0047_merge_20200408_1643'),
    ]

    operations = [
    ]
