# Generated by Django 2.0.13 on 2020-09-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0049_merge_20200408_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourconferencepaper',
            name='subject',
            field=models.ManyToManyField(blank=True, default=None, help_text='関連する研究テーマを登録してください．', related_name='conference_subject', to='public.Research', verbose_name='関連テーマ'),
        ),
    ]
