# Generated by Django 2.0.13 on 2019-06-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='フォーマット名')),
                ('category', models.IntegerField(choices=[(11, '研究室内 論文誌論文'), (12, '研究室内 国際会議論文'), (13, '研究室内 国内会議論文')], default=None, help_text='出力対象のデータの種類を入力してください．', verbose_name='出力データ')),
                ('header', models.TextField(blank=True, help_text='出力ファイルのヘッダを入力してください．', verbose_name='ヘッダ')),
                ('format', models.TextField(help_text='データを出力フォーマットを記述してください．', verbose_name='出力フォーマット')),
                ('footer', models.TextField(blank=True, help_text='出力ファイルのフッタを入力してください．', verbose_name='フッタ')),
            ],
        ),
    ]
