# Generated by Django 2.0.13 on 2019-06-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='category',
            field=models.IntegerField(choices=[(11, '研究室内 論文誌論文'), (12, '研究室内 会議発表')], default=None, help_text='出力対象のデータの種類を入力してください．', verbose_name='出力データ'),
        ),
    ]
