# Generated by Django 2.0.13 on 2019-06-08 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('output', '0003_auto_20190608_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_format', to=settings.AUTH_USER_MODEL, verbose_name='登録ユーザ'),
        ),
    ]
