# Generated by Django 2.0.13 on 2019-06-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0006_auto_20190608_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='descending_order',
            field=models.BooleanField(null=True, default=None, help_text='デフォルトは並び替えキーで昇順に並べます．降順にする場合はチェックを入れてください．', verbose_name='降順'),
        ),
        migrations.AddField(
            model_name='format',
            name='sort_key',
            field=models.CharField(blank=True, help_text='並び順の基準にするキーを入力してください', max_length=200, verbose_name='並び替えキー'),
        ),
    ]
