# Generated by Django 2.0.13 on 2019-06-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0007_auto_20190614_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='category',
            field=models.CharField(choices=[('our_journal_paper', '研究室内 論文誌論文'), ('our_conference_paper', '研究室内 会議発表'), ('award', '受賞')], default=None, help_text='出力対象のデータの種類を入力してください．', max_length=20, verbose_name='出力データ'),
        ),
        migrations.AlterField(
            model_name='format',
            name='sort_key',
            field=models.CharField(blank=True, help_text='並び順の基準にするキーを変数で入力してください', max_length=200, verbose_name='並び替えキー'),
        ),
    ]
