# Generated by Django 2.0.13 on 2019-07-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0008_auto_20190617_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='extension',
            field=models.CharField(default='csv', help_text='出力ファイルの拡張子を指定してください．', max_length=10, verbose_name='拡張子'),
        ),
        migrations.AlterField(
            model_name='format',
            name='category',
            field=models.CharField(choices=[('our_journal_paper', '研究室内 論文誌論文'), ('our_conference_paper', '研究室内 会議発表'), ('journal_paper', '論文誌論文'), ('conference_paper', '会議発表'), ('award', '受賞')], default=None, help_text='出力対象のデータの種類を入力してください．', max_length=20, verbose_name='出力データ'),
        ),
    ]
