# Generated by Django 2.0.13 on 2019-08-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0009_auto_20190703_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='category',
            field=models.CharField(choices=[('our_journal_paper', '研究室内 論文誌論文'), ('our_conference_paper', '研究室内 会議発表'), ('our_int_conf_paper', '研究室内 国際会議発表'), ('our_dom_conf_paper', '研究室内 国内会議発表'), ('journal_paper', '論文誌論文'), ('conference_paper', '会議発表'), ('url_reference', 'ウェブサイト'), ('award', '受賞')], default=None, help_text='出力対象のデータの種類を入力してください．', max_length=20, verbose_name='出力データ'),
        ),
    ]
