# Generated by Django 2.0.13 on 2020-07-18 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import market.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='商品名')),
                ('kyash_url', models.URLField(blank=True, verbose_name='URL (Kyash)')),
                ('kyash_qr', models.ImageField(blank=True, help_text='支払いに使うQRコード', verbose_name='決済QRコード')),
                ('description', models.TextField(blank=True, verbose_name='商品説明')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_item', to=settings.AUTH_USER_MODEL, verbose_name='管理者')),
            ],
        ),
    ]
