# Generated by Django 2.0.13 on 2020-07-19 17:37

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='paypay_qr',
            field=models.ImageField(blank=True, help_text='PayPayの支払いに使うQRコード(自動生成)', verbose_name='決済QRコード (PayPay)'),
        ),
        migrations.AddField(
            model_name='item',
            name='paypay_url',
            field=models.URLField(blank=True, verbose_name='URL (PayPay)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='kyash_qr',
            field=models.ImageField(blank=True, help_text='Kyashの支払いに使うQRコード(自動生成)', verbose_name='決済QRコード (Kyash)'),
        ),
    ]
