# Generated by Django 2.0.13 on 2020-09-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200719_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.IntegerField(choices=[('Beverages', 'ソフトドリンク'), ('Alcohol-drinks', 'アルコール飲料'), ('Snacks', '食べ物')], default=9, verbose_name='カテゴリ'),
        ),
    ]
