# Generated by Django 2.0.13 on 2020-09-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Beverages', 'ソフトドリンク'), ('Alcohol-drinks', 'アルコール飲料'), ('Snacks', '食べ物')], default=None, max_length=20, verbose_name='カテゴリ'),
        ),
    ]
