# Generated by Django 2.0.13 on 2020-09-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200913_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=True, help_text='非表示にする場合はチェックを外してください．', verbose_name='マーケットに表示'),
        ),
    ]
