# Generated by Django 2.0.13 on 2020-10-04 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20201002_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(help_text='支払先を指定するために，管理者は別途，<a href="/myaccount" target="_blank">アカウント設定</a>からKyash QRコードまたはPayPay IDを登録する必要があります．', on_delete=django.db.models.deletion.CASCADE, related_name='user_item', to=settings.AUTH_USER_MODEL, verbose_name='管理者'),
        ),
    ]
