# Generated by Django 2.0.13 on 2019-11-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('start_date', models.DateField(verbose_name='開始年月日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了年月日')),
            ],
        ),
    ]
