# Generated by Django 2.0.13 on 2019-11-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[('my_kakenhi', '科研費 代表'), ('other_kakenhi', '科研費 分担'), ('others', 'その他')], default='my_kakenhi', verbose_name='カテゴリ')),
                ('fund_name', models.CharField(max_length=100, verbose_name='研究助成名称')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('start_date', models.DateField(verbose_name='開始年月日')),
                ('end_date', models.DateField(verbose_name='終了年月日')),
            ],
        ),
    ]
