# Generated by Django 2.0.13 on 2019-11-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='category',
            field=models.CharField(choices=[('my_kakenhi', '科研費 代表'), ('other_kakenhi', '科研費 分担'), ('others', 'その他')], default='my_kakenhi', max_length=15, verbose_name='カテゴリ'),
        ),
    ]
