# Generated by Django 2.0.13 on 2019-11-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_collaboration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboration',
            old_name='fund_name',
            new_name='company',
        ),
    ]
