# Generated by Django 2.0.13 on 2019-11-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20191114_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='role',
            field=models.CharField(choices=[('principal', '代表'), ('co-investigator', '分担')], default='principal', max_length=15, verbose_name='代表/分担'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fund',
            name='category',
            field=models.CharField(choices=[('kakenhi', '科研費'), ('internal', '学内資金'), ('others', 'その他')], max_length=15, verbose_name='カテゴリ'),
        ),
    ]
