# Generated by Django 2.0.13 on 2021-01-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20191117_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalactivity',
            name='title',
            field=models.CharField(max_length=400, verbose_name='タイトル'),
        ),
    ]
